### ISSUE TITLE
Can you use Spring Cloud GCP to enable Stackdriver trace from a K8 based app?

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-gcp#1083]
I've added Spring Cloud GCP dependencies to my app running in GKE:

```
 <dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-gcp-starter-trace</artifactId>
  </dependency>

  <dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-gcp-starter-logging</artifactId>
  </dependency>
```

and:

```
  <dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-kubernetes</artifactId>
   <version>0.3.0.RELEASE</version>
  </dependency>
```

Do I need to do anything else to get Trace to work? Is this supported at all?

**Comment by meltsufin** [comment]
That works locally and should work on GKE as well. We're investigating. Thanks for reporting!

**Comment by Alos** [comment]
I got this working now! The problem was on our end. We failed to inject the `RestTemplate`  exposed by the `@Bean` annotation and thus we were not getting any propagation of headers. Stackdriver is now showing all the jumps in our services :)

**Comment by meltsufin** [comment]
I'm glad it's resolved for you, but we're still having issues with our Trace sample app not working on App Engine Flex. However, that's probably unrelated to your issue.

**Comment by michael-barker** [comment]
@meltsufin When using Spring Cloud GCP in Kubernetes, I get this exception when the spans are being sent to Stackdriver.

```
2018-10-16 04:02:17.257 DEBUG [-,,,] 1 --- [r-stackdriver}}] z.r.AsyncReporter$BoundedAsyncReporter   : Dropped 2 spans due to StatusRuntimeException(INTERNAL: Panic! This is a bug!)
```

```
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
	at zipkin2.reporter.stackdriver.internal.AwaitableUnaryClientCallListener.onClose(AwaitableUnaryClientCallListener.java:89) ~[zipkin-sender-stackdriver-0.6.4.jar:na]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.14.0.jar:1.14.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.AbstractMethodError: io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(Ljava/net/SocketAddress;Lio/grpc/internal/ClientTransportFactory$ClientTransportOptions;)Lio/grpc/internal/ConnectionClientTransport;
	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:47) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:238) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:206) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1417) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:74) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:106) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1286) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:1230) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1290) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:251) ~[grpc-core-1.14.0.jar:1.14.0]
```

**Comment by michael-barker** [comment]
@meltsufin I have my sample rate set to 1.0 for testing but starting the app up and sending a single request causes this error.

**Comment by meltsufin** [comment]
I think we need a separate issue for this, and a simple app the reproduces the behavior.

**Comment by michael-barker** [comment]
@meltsufin I created #1120.
