### ISSUE TITLE
database creation using databaseadminclient

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1093]
We are getting the below exception when giving "-" in the dbnamen. Documentation states its supported

ava.lang.AssertionError: Exception while running createDB : com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
    at com.homedepot.loyalty.integration.IntegrationTestRunner.beforeSuite(IntegrationTestRunner.java:16)
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
    at com.homedepot.loyalty.integration.IntegrationTestRunner.beforeSuite(IntegrationTestRunner.java:16)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").

**Comment by ChengyuanZhao** [comment]
This looks like it's coming straight from the client library. I'll make an issue with them.

**Comment by ChengyuanZhao** [comment]
Actually @vineela-gampa our own integration test actually uses a DB name that has a "-" in it  
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/test/resources/application-test.properties

Could you share more of your config or code?

**Comment by vineela-gampa** [comment]
@ChengyuanZhao thsi is the error we are getting

ava.lang.AssertionError: Exception while running createDB : com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
    at com.homedepot.loyalty.integration.IntegrationTestRunner.beforeSuite(IntegrationTestRunner.java:16)
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
    at com.homedepot.loyalty.integration.IntegrationTestRunner.beforeSuite(IntegrationTestRunner.java:16)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE DATABASE integrationtest-db : Syntax error on line 1, column 32: Expecting 'EOF' but found an unknown character ("-").

**Comment by vineela-gampa** [comment]
Yes we are submitting DDL directly.

**Comment by ChengyuanZhao** [comment]
@vineela-gampa If you are sending DDL directly then you probably need to escape the special characters correctly. Spring Data Spanner doesn't seem to be related to the issue in this case, so I will be closing the issue.
