### ISSUE TITLE
Problems with logback-json-appender

### ISSUE THREAD

**Issue by triberraar** [spring-cloud/spring-cloud-gcp#1137]
I am trying to get stackdriver to understand my log files, I am using the  CONSOLE_JSON appender of `logback-json-appender.xml` and my app is running on app engine flexible.
And i am using dependency management from  `org.springframework.cloudspring-cloud-gcp-dependencies:1.0.0.RELEASE`.
However stackdriver doesn't seem to interpret it at all and just takes the whole json as a log line see [https://ibb.co/hZqDgV](url)

I also tried using `org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml` but that one blows up on my build server. It works locally but not on our bitbucket pipeline, so i think there must be some environment variable that is missing?
The exception i get there is:
```
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@9:16 - RuntimeException in Action for tag [appender] java.lang.NullPointerException
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:82)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:264)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:237)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:200)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:364)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
...
```

I am using these appenders in the `logback-spring.xml` so i can use profiles eg
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-json-appender.xml"/>

    <springProfile name="dev,performance">
            <root level="INFO">
                <appender-ref ref="CONSOLE_JSON"/>
            </root>
        </springProfile>
        <springProfile name="local">
            <root level="INFO">
                <appender-ref ref="CONSOLE"/>
            </root>
        </springProfile>
        <springProfile name="test">
            <root level="INFO">
                <appender-ref ref="CONSOLE"/>
            </root>
        </springProfile>
</configuration>
```

So am i doing something wrong or?

**Comment by meltsufin** [comment]
The only thing that stands out to me from your configuration is the use of `springProfile` in the `logback-spring.xml`. Maybe that has something to do with the exception you're getting because it seems to happen during logging initialization.
We do have a [logging sample](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample) app that runs on App Engine Flex. If you can modify it to reproduce your issue, it would help us troubleshoot. Thanks!

**Comment by meltsufin** [comment]
Please re-open if you still have the issue.
