### ISSUE TITLE
Allow enums as arguments in query methods

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1166]
Could you please make possible use enums as arguments in query methods.
For example, we have a model:

```
Entity(name = "singers")
public class Singer {

    @Id
    @Field(name = "singer_id")
    private String singerId;

    @Field(name = "sex")
    private Sex sex; //enum
}
```

Datastore repository has a simple search method:

```
public interface SingerRepository extends DatastoreRepository<Singer, String> {
    Collection<Singer> findBySex(Sex sex);
}
```
An exception occurs after executing this method. Searching by string works fine. 
Enum arguments can be emulated with [name()](https://docs.oracle.com/javase/10/docs/api/java/lang/Enum.html#name()) method.

```

Caused by: org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class com.example.Sex to Datastore supported type.
	at org.springframework.cloud.gcp.data.datastore.core.convert.DatastoreNativeTypes.wrapValue(DatastoreNativeTypes.java:105) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.lambda$applySelectWithFilter$1(PartTreeDatastoreQuery.java:190) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
```

**Comment by ChengyuanZhao** [comment]
Made a PR for this. should be in shortly.
