### ISSUE TITLE
Slice and Page return types are not supported in pagination

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1167]
Could you please make possible use Slice and Page as return type.
[Spring Data Reference with supported types](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.special-parameters)

For example, we have a model:

```
Entity(name = "singers")
public class Singer {

    @Id
    @Field(name = "singer_id")
    private String singerId;

    @Field(name = "first_name")
    private String firstName;
}
```
Datastore repository has a simple search method (with pagination):
```
public interface SingerRepository extends DatastoreRepository<Singer, String> {
    Slice<Singer> findAllByFirstName(String firstName, Pageable pageable);
}
```
An exception occurs after executing this method. List as return type works fine. 

```
Caused by: org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class java.util.ArrayList to class com.example.Singer
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnReadSingle(TwoStepsConversions.java:231) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:164) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:105) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.convertResultCollection(PartTreeDatastoreQuery.java:144) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.execute(PartTreeDatastoreQuery.java:139) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy64.findAllByLastName(Unknown Source) ~[na:na]
	at com.example.DatastoreRepositoryExample.lambda$commandLineRunner$0(DatastoreRepositoryExample.java:64) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	... 5 common frames omitted

```

**Comment by meltsufin** [comment]
@ChengyuanZhao @dmitry-s
