### ISSUE TITLE
Query methods don't work with arguments

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1168]
Query methods don't work with arguments
For example, we have a model:
```
Entity(name = "singers")
public class Singer {

    @Id
    @Field(name = "singer_id")
    private Long singerId;

}
```
Datastore repository has a simple search method:

```
public interface SingerRepository extends DatastoreRepository<Singer, Long> {

    @Query("SELECT * FROM singers WHERE singer_id = :singerId")
    Collection<Singer> findByIdExample(@Param("singerId") Long singerId);

}
```
An exception occurs after executing this method. 
Look's like query was sent to Datastore without any changes.

```
Caused by: com.google.datastore.v1.client.DatastoreException: Lexical error at line 1, column 41.  Encountered: ":" (58), after : ""
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226) ~[datastore-v1-proto-client-1.6.0.jar:na]
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275) ~[datastore-v1-proto-client-1.6.0.jar:na]
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186) ~[datastore-v1-proto-client-1.6.0.jar:na]
	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119) ~[datastore-v1-proto-client-1.6.0.jar:na]
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:180) ~[google-cloud-datastore-1.45.0.jar:1.45.0]
	... 31 common frames omitted
```

**Comment by ChengyuanZhao** [comment]
@sergeymeshkov parameters right now use the Cloud Datastore tag format `@tag` instead of `:tag`. 
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-docs/src/main/asciidoc/datastore.adoc

We do have a ticket for supporting the Spring SPEL style tags (it is coming soon), and you will be able to use all the normal SPEL-expression style tags.
