### ISSUE TITLE
Support LocalDateTime as search argument in query methods

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1275]
Is it possible to support LocalDateTime as a search argument in Spring Data query methods?

For example, we have a model:

```
Entity(name = "singers")
public class Singer { 

    @Id     
    @Field(name = "singer_id")
    private String singerId;

    @Field(name = "created_date")
    private LocalDateTime createdDate;
}
```

Datastore repository has a search method:
`List<Singer> findAllByCreatedDateLessThan(LocalDateTime date);`

After calling the method an error occurs:

```
Caused by: org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class java.time.LocalDateTime to Datastore supported type.
	at org.springframework.cloud.gcp.data.datastore.core.convert.DatastoreNativeTypes.wrapValue(DatastoreNativeTypes.java:142) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181129.214831-188.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.lambda$applySelectWithFilter$1(PartTreeDatastoreQuery.java:207) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181129.214831-188.jar:1.1.0.BUILD-SNAPSHOT]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517) ~[na:na]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.applySelectWithFilter(PartTreeDatastoreQuery.java:221) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181129.214831-188.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.applyQueryBody(PartTreeDatastoreQuery.java:160) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181129.214831-188.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.execute(PartTreeDatastoreQuery.java:129) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181129.214831-188.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy67.findAllByCreatedDateLessThan(Unknown Source) ~[na:na]
	at com.example.DatastoreRepositoryExample.lambda$commandLineRunner$0(DatastoreRepositoryExample.java:80) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	... 5 common frames omitted
```

**Comment by meltsufin** [comment]
Have you considered adding a [custom converter](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/datastore.adoc#custom-types) for it?
Otherwise, maybe we should support it out of the box. WDYT @dmitry-s @ChengyuanZhao?

**Comment by ChengyuanZhao** [comment]
Taking a look

**Comment by ChengyuanZhao** [comment]
Currently we don't use custom converters for query-method params, and we instead look up directly in a map of directly supported types. Let me look into what it would take to use custom converters here, too.
