### ISSUE TITLE
Getting a single entry findOneBy... / findFirstBy... results in DatastoreDataException

### ISSUE THREAD

**Issue by GerroDen** [spring-cloud/spring-cloud-gcp#1471]
Hello,

I want to load a single entry by a repository like this:

```
public interface UserRepository extends DatastoreRepository<User, Long> {
	User findFirstByGoogleAccountId(String googleAccountId);
}
```

But a call of this method leads to this exception and stacktrace:
```
org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class java.util.ArrayList to class repositories.user.User                                                   
     at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnReadSingle(TwoStepsConversions.java:231) ~[org_springframework_cloud_spring_cloud_gcp_data_datastore.jar:1.1.0.RE 
     at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:164) ~[org_springframework_cloud_spring_cloud_gcp_data_datastore.jar:1.1.0.RELEASE] 
     at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:105) ~[org_springframework_cloud_spring_cloud_gcp_data_datastore.jar:1.1.0.RELEASE] 
     at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.convertResultCollection(PartTreeDatastoreQuery.java:211) ~[org_springframework_cloud_spring_cloud_gcp_data_datastor 
     at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.execute(PartTreeDatastoreQuery.java:180) ~[org_springframework_cloud_spring_cloud_gcp_data_datastore.jar:1.1.0.RELE 
     at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.execute(PartTreeDatastoreQuery.java:131) ~[org_springframework_cloud_spring_cloud_gcp_data_datastore.jar:1.1.0.RELE 
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605) ~[org_springframework_data_spring_data_commons.jar: 
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[org_springframework_data_spring_data_commo 
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[org_springframework_data_spring_data_commons.jar:2. 
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                            
     at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[org_springframework_data_spring_data_commons.jar:2.1.4.RELEASE]      
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                            
     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                          
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                            
     at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[org_springframework_data_spring_data_ 
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                            
     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[org_springframework_spring_aop.jar:5.1.5.RELEASE]                                                             
     at com.sun.proxy.$Proxy59.findFirstByGoogleAccountId(Unknown Source) ~                                                                                                                                      
```

Neither does `findOneBy...` nor result type `Optional<User>` works.
Isn't that the usual way to load a single entry in JPA?

**Comment by meltsufin** [comment]
@ChengyuanZhao @dmitry-s PTAL.

**Comment by dmitry-s** [comment]
I was able to reproduce the issue and working on fix.

**Comment by ChengyuanZhao** [comment]
Sounds like this would cover this issue as well: 
https://github.com/spring-cloud/spring-cloud-gcp/issues/1350

That was also a request to support single-item return type outside of lists.

**Comment by GerroDen** [comment]
yes, #1350 is the practically the same issue with a different description :)
