### ISSUE TITLE
Spanner - seems to check for non-null values even though the column is nullable

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1511]
I have a column that's nullable and have stored null value. When reading from Spring Data Repository (via Rest Repository), it throws exception due to the null value.

```
java.lang.NullPointerException: Column name contains NULL value
	at com.google.cloud.spanner.AbstractStructReader.checkNonNull(AbstractStructReader.java:336) ~[google-cloud-spanner-1.4.0.jar:1.4.0]
	at com.google.cloud.spanner.AbstractStructReader.checkNonNullOfType(AbstractStructReader.java:348) ~[google-cloud-spanner-1.4.0.jar:1.4.0]
	at com.google.cloud.spanner.AbstractStructReader.getString(AbstractStructReader.java:139) ~[google-cloud-spanner-1.4.0.jar:1.4.0]
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructAccessor.getSingleValue(StructAccessor.java:136) ~[spring-cloud-gcp-data-spanner-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.readSingleWithConversion(StructPropertyValueProvider.java:104) ~[spring-cloud-gcp-data-spanner-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.getPropertyValue(StructPropertyValueProvider.java:88) ~[spring-cloud-gcp-data-spanner-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.getPropertyValue(StructPropertyValueProvider.java:38) ~[spring-cloud-gcp-data-spanner-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.data.mapping.model.PersistentEntityParameterValueProvider.getParameterValue(PersistentEntityParameterValueProvider.java:71) ~[spring-data-commons-2.1.5.RELEASE.jar:2.1.5.RELEASE]
...
```

**Comment by ChengyuanZhao** [comment]
@saturnism I remember fixing a bug like this a few weeks/months ago. Are you using the most recent version?

**Comment by saturnism** [comment]
i'm using the version specified in Greenwich.SR1 release train. which is pointing to `org.springframework.cloud:spring-cloud-gcp-starter-data-spanner:jar:1.1.1.RELEASE`

**Comment by ChengyuanZhao** [comment]
@saturnism ah shoot looks like this fix is only in 1.2.0 BUILD SNAPSHOT and wasn't ported back to the 1.1 versions.

**Comment by meltsufin** [comment]
@ChengyuanZhao Can you apply the fix in 1.1.x please so that we get it in the next SR? Thanks!

**Comment by saturnism** [comment]
+1 :D

**Comment by saturnism** [comment]
thnx for backporting the fix! can this be closed?

**Comment by ChengyuanZhao** [comment]
fix has been applied !
