### ISSUE TITLE
Support Pagination for @Query annotated methods

### ISSUE THREAD

**Issue by GerroDen** [spring-cloud/spring-cloud-gcp#1570]
I'd like to do a custom query on a repository which i need to search by ancestor releations.
So my method looks like this:
```java
	@Query("SELECT * FROM child WHERE __key__ HAS ANCESTOR @parentKey")
	Page<Post> findAllByParentKeyOrderByNameDesc(@Param("parentKey") Key parentKey, Pageable pageable);
```
([GQL-Docs](https://cloud.google.com/datastore/docs/reference/gql_reference#operators_and_comparisons))

But using this method with a REST endpoint results in a `DatastoreDataException`:
```plain
org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class org.springframework.data.domain.PageRequest to Datastore supported type.
     at org.springframework.cloud.gcp.data.datastore.core.convert.DatastoreNativeTypes.wrapValue(DatastoreNativeTypes.java:166)
     at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnWriteSingle(TwoStepsConversions.java:320)
     at org.springframework.cloud.gcp.data.datastore.repository.query.GqlDatastoreQuery.bindArgsToGqlQuery(GqlDatastoreQuery.java:233)
     at org.springframework.cloud.gcp.data.datastore.repository.query.GqlDatastoreQuery.execute(GqlDatastoreQuery.java:118)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
     at com.sun.proxy.$Proxy97.findAllByParentKeyOrderByNameDesc(Unknown Source)
```

Am i doing this wrong?

**Comment by dmitry-s** [comment]
Annotated query methods do not support that at the moment, but I'm working on it. 

Currently you can use Pageable with all the other repository methods. I would recommend the latest version from master branch because it uses cursors internally.

**Comment by GerroDen** [comment]
So is there a way to get a `__key__ HAS ANCESTOR` by repository method naming convention?
I guessed this is quite special for Google Datastore and so not yet supported. I cannot find a hint for this in the docs.
So i guess i have to write a custom repository that does the paged query with low level Google API for now.

I appreciate the support for this project :)
Thank you.

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao ?

**Comment by ChengyuanZhao** [comment]
@GerroDen 

The naming convention query methods (the ones solely based on method name and without `@Query` annotation) are from Spring Data's core name parsing and they do not have anything specific to Datastore. As a result, there isn't a way to specify that ancestor filter in the method name.
