### ISSUE TITLE
Sending logs with logback appender disables custom truststore

### ISSUE THREAD

**Issue by markuskruse** [spring-cloud/spring-cloud-gcp#1655]
Our application connects to several other services that has their own root certificates. That works well with a custom truststore.

    @PostConstruct
    public void configureSSL() {
        System.setProperty("javax.net.ssl.trustStore", trustStore);
        System.setProperty("javax.net.ssl.trustStorePassword", trustStorePassword);
    }

I can import this library without problem:

    compile 'org.springframework.cloud:spring-cloud-gcp-starter-logging:1.0.0.RELEASE'

I can import the logback file (from logback.xml):

    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />

But if I also use this appender, the truststore isn't working anymore:

    <root level="INFO">
        <appender-ref ref="STACKDRIVER" />
        <appender-ref ref="STDOUT" />
    </root>

I don't know if the appender used above is conflicting on a network level or changing the truststore or what happens, but I get this error:
```
org.springframework.ws.client.WebServiceIOException: I/O error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:561)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:383)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:373)
	at com.company.service.OmSoapAdaptor.marshalSendAndReceive(OmSoapAdaptor.java:34)
	at com.company.service.OmHealthChecker.pingOm(OmHealthChecker.java:72)
	at com.company.service.OmHealthChecker.checkHealth(OmHealthChecker.java:45)
	at com.company.service.OmClient.checkHealth(OmClient.java:105)
	at com.company.PrintServiceHealthIndicator.health(PrintServiceHealthIndicator.java:24)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:98)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:246)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:126)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:99)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:642)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:461)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:361)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:241)
	at org.springframework.ws.transport.http.HttpUrlConnection.getRequestOutputStream(HttpUrlConnection.java:89)
	at org.springframework.ws.transport.AbstractSenderConnection$RequestTransportOutputStream.createOutputStream(AbstractSenderConnection.java:87)
	at org.springframework.ws.transport.TransportOutputStream.getOutputStream(TransportOutputStream.java:41)
	at org.springframework.ws.transport.TransportOutputStream.write(TransportOutputStream.java:64)
	at com.sun.xml.messaging.saaj.soap.MessageImpl.writeTo(MessageImpl.java:1417)
	at org.springframework.ws.soap.saaj.SaajSoapMessage.writeTo(SaajSoapMessage.java:272)
	at org.springframework.ws.transport.AbstractWebServiceConnection.send(AbstractWebServiceConnection.java:46)
	at org.springframework.ws.client.core.WebServiceTemplate.sendRequest(WebServiceTemplate.java:658)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:606)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
	... 41 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:626)
	... 66 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 72 more

```

**Comment by dzou** [comment]
At a surface level, you can try upgrading the [version](
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-gcp-starter-logging) to see if that fixes it for you; i.e. 
`compile 'org.springframework.cloud:spring-cloud-gcp-starter-logging:1.1.1.RELEASE'`

Unfortunately I don't think our team is too familiar with truststore; we might need a reproducible example to help with debugging further. Perhaps @meltsufin can comment if he's seen something similar before.

**Comment by meltsufin** [comment]
It's very strange because logging is not involved in this stack trace at all.
If I understand correctly, the problem only appears when you use the stackdriver Logback appender.
In an effort to isolate the problem, does everything start working if you only remove this line?
```xml
    <appender-ref ref="STACKDRIVER" />
```
Nothing in our code really touches anything related to the truststore.
Perhaps it's something in the [client library](https://github.com/googleapis/google-cloud-java) layers and GRPC.

**Comment by markuskruse** [comment]
Thanks for the quick response guys. I tried upgrading but it didn't help.

@meltsufin Yes, it is that exact row that breaks it.

So if I comment it out, it works. But there is no logs sent.

        

I am creating a little test project to show the problem in isolation.

**Comment by markuskruse** [comment]
Example application here:

https://github.com/markuskruse/truststore-example

**Comment by meltsufin** [comment]
@markuskruse Thanks for the example. I'm able to reproduce the issue, but still trying to identify the root cause. I'll give you an update soon.

**Comment by meltsufin** [comment]
I experimented a bit more and I still don't know what exactly is happening. It looks like GRPC, which is used for Logging and pretty much all other GCP services might be hijacking the Java SSL networking configuration that is normally based on the properties you're using `javax.net.ssl.trustStore` and `javax.net.ssl.trustStorePassword`. You may want to look for alternative ways to specify the trustStore when creating an HTTP request.

@ejona86 Any thoughts on this?

**Comment by markuskruse** [comment]
Maybe this bug is belonging more on GRPC?

**Comment by markuskruse** [comment]
I worked around it using this answer:
https://stackoverflow.com/questions/2419791/using-webservicetemplate-with-a-keystore
Thanks for the effort guys.

**Comment by meltsufin** [comment]
Thanks a lot for the update! I'll keep the issue open though in case someone wants take on the challenge to get to the bottom of this.

**Comment by meltsufin** [comment]
@ejona86 Do you have any thoughts on this? Should we open an issue in the grpc-java repo?

**Comment by elefeint** [comment]
Please reopen if the workaround provided is insufficient.

**Comment by ejona86** [comment]
Sorry, this was routed to my personal inbox which is a blackhole.

I don't think this is a gRPC problem. I think the problem is an initialization order problem; `@Configuration` runs too late.

The JVM TLS configuration is loaded lazily, and when the logging code loads it loads gRPC which loads the TLS configuration. It sees the _default_ javax.net.ssl.trustStore/javax.net.ssl.trustStorePassword. The later `System.setProperty()` has no effect because nothing reads it after that point in time.

When you disable the gcp logging, the JVM TLS configuration is loaded _later_, at the point of the HTTP call, after the `System.setProperty()`.

The proper fix here is to set the properties sooner. For example, by adding in the `build.gradle`:
```
bootRun {
  jvmArgs "-Djavax.net.ssl.trustStore=./badsslcom.jks", "-Djavax.net.ssl.trustStorePassword=changeit"
}
```

However, that will break the GCP logging because the truststore no longer has the normal CAs; you'd probably want to copy the default truststore and re-import the self-signed cert. However, the fact it breaks GCP logging whereas the `@Configuration` did not clearly shows that the setProperty is being called too late.

**Comment by elefeint** [comment]
@ejona86 Thank you for the thorough analysis -- this will help us for all future keystore-related issues.
To summarize, there are two approaches to resolving the issues:
1) set custom truststore property when starting JVM or at Spring bootstrapping phase, while ensuring that the truststore contains all standard CAs.
2) Leave the default trustore alone and configure the higher-level functionality (in this case `WebServiceTemplate`) to use the custom keystore, per [Stack Overlow answer](https://stackoverflow.com/questions/2419791/using-webservicetemplate-with-a-keystore).
