### ISSUE TITLE
Datastore Sample failing

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1692]
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.SingerRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1193)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:623)
```

@ChengyuanZhao @dmitry-s PTAL

**Comment by ChengyuanZhao** [comment]
I've gone as far back as this commit on master that used to work but also no longer does

![image](https://user-images.githubusercontent.com/29288945/58272460-91515300-7d5c-11e9-893e-70f67766c2dd.png)


I'll try to use some older versions of dependencies...

**Comment by elefeint** [comment]
Since my face made an appearance... Spring-boot bom upgraded to spring-data Moore-M4 recently: https://github.com/spring-projects/spring-boot/issues/16574

**Comment by ChengyuanZhao** [comment]
hahahaha thank you Detective Elena !!
