### ISSUE TITLE
PubSubMessageChannelBinderTests.testAfterUnbindConsumer  fails on master

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-gcp#1715]
```
[INFO] Running org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorTests
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.016 s - in org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorTests
[INFO] Running org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderTests
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.521 s <<< FAILURE! - in org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderTests
[ERROR] testAfterUnbindConsumer  Time elapsed: 0.51 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/integration/endpoint/Pausable
	at org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderTests.before(PubSubMessageChannelBinderTests.java:63)
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.endpoint.Pausable
	at org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinderTests.before(PubSubMessageChannelBinderTests.java:63)
```

**Comment by meltsufin** [comment]
@artembilan Are we on the wrong version of Spring Integration somehow?

**Comment by artembilan** [comment]
See my PR https://github.com/spring-cloud/spring-cloud-gcp/pull/1714. 

I think our master is definitely on wrong dependency.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-gcp/commit/85ba657b4f250fe71911100f94fca625d0149356
