### ISSUE TITLE
spring-cloud-gcp-firestore-sample (1.2.0.M1) failed to start in PCF env

### ISSUE THREAD

**Issue by stevenweili** [spring-cloud/spring-cloud-gcp#1753]
I encountered issue when doing integration with firestore on PCF, I can reproduce it using the sample app:
https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-firestore-sample
Base on it, I only change version to 1.2.0.M1
`<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-gcp-dependencies</artifactId>
                <version>1.2.0.M1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>`

On PCF, 
the firestore service was bound to the app, the env VCAP_SERVICES seems good

 `"VCAP_SERVICES": {
      "google-firestore": [
        {
          "label": "google-firestore",
          "provider": null,
          "plan": "default",
          "name": "catalog-firestore",
          "tags": [
            "gcp",
            "firestore",
            "preview",
            "beta"
          ],
          "instance_name": "catalog-firestore",
          "binding_name": null,
          "credentials": {
            "Email": "pcf-binding-9da49fcb@pcf-dev-01-17031.iam.gserviceaccount.com",
            "Name": "pcf-binding-9da49fcb",
            "PrivateKeyData": "IWASHIDDEN" "ProjectId": "pcf-dev-01-17031",
            "UniqueId": "100112069244886737898"
          },
          "syslog_drain_url": null,
          "volume_mounts": []
        }
      ]
    }
  }`

error:
`
2019-07-22T10:20:07.642-07:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:20:07.642-07:00 [APP/PROC/WEB/0] [OUT] at com.google.cloud.firestore.FirestoreOptions$Builder.build(FirestoreOptions.java:215) ~[google-cloud-firestore-1.8.0.jar!/:1.8.0]
2019-07-22T10:20:07.642-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.autoconfigure.firestore.GcpFirestoreAutoConfiguration.firestoreOptions(GcpFirestoreAutoConfiguration.java:78) ~[spring-cloud-gcp-autoconfigure-1.2.0.M1.jar!/:1.2.0.M1]
`

full stack error:
`2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'firestoreSampleApp': Unsatisfied dependency expressed through field 'firestore'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'firestore' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/firestore/GcpFirestoreAutoConfiguration.class]: Unsatisfied dependency expressed through method 'firestore' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firestoreOptions' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/firestore/GcpFirestoreAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.firestore.FirestoreOptions]: Factory method 'firestoreOptions' threw exception; nested exception is java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] 2019-07-22 17:24:38.585 ERROR 15 --- [ main] o.s.boot.SpringApplication : Application run failed
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.example.FirestoreSampleApp.main(FirestoreSampleApp.java:48) [classes/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [app/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [app/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'firestore' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/firestore/GcpFirestoreAutoConfiguration.class]: Unsatisfied dependency expressed through method 'firestore' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firestoreOptions' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/firestore/GcpFirestoreAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.firestore.FirestoreOptions]: Factory method 'firestoreOptions' threw exception; nested exception is java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] ... 26 common frames omitted
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firestoreOptions' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/firestore/GcpFirestoreAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.firestore.FirestoreOptions]: Factory method 'firestoreOptions' threw exception; nested exception is java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] ... 39 common frames omitted
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.firestore.FirestoreOptions]: Factory method 'firestoreOptions' threw exception; nested exception is java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] ... 53 common frames omitted
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.RuntimeException: Failed to obtain credentials
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.cloud.firestore.FirestoreOptions$Builder.build(FirestoreOptions.java:215) ~[google-cloud-firestore-1.8.0.jar!/:1.8.0]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.autoconfigure.firestore.GcpFirestoreAutoConfiguration.firestoreOptions(GcpFirestoreAutoConfiguration.java:78) ~[spring-cloud-gcp-autoconfigure-1.2.0.M1.jar!/:1.2.0.M1]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.autoconfigure.firestore.GcpFirestoreAutoConfiguration$$EnhancerBySpringCGLIB$$20258fc3.CGLIB$firestoreOptions$1(<generated>) ~[spring-cloud-gcp-autoconfigure-1.2.0.M1.jar!/:1.2.0.M1]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.autoconfigure.firestore.GcpFirestoreAutoConfiguration$$EnhancerBySpringCGLIB$$20258fc3$$FastClassBySpringCGLIB$$1f4b0efc.invoke(<generated>) ~[spring-cloud-gcp-autoconfigure-1.2.0.M1.jar!/:1.2.0.M1]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.autoconfigure.firestore.GcpFirestoreAutoConfiguration$$EnhancerBySpringCGLIB$$20258fc3.firestoreOptions(<generated>) ~[spring-cloud-gcp-autoconfigure-1.2.0.M1.jar!/:1.2.0.M1]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] ... 54 common frames omitted
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:132) ~[google-auth-library-oauth2-http-0.16.1.jar!/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:115) ~[google-auth-library-oauth2-http-0.16.1.jar!/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:88) ~[google-auth-library-oauth2-http-0.16.1.jar!/:na]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:67) ~[gax-1.45.0.jar!/:1.45.0]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.gcp.core.DefaultCredentialsProvider.getCredentials(DefaultCredentialsProvider.java:67) ~[spring-cloud-gcp-core-1.2.0.M1.jar!/:1.2.0.M1]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] at com.google.cloud.firestore.FirestoreOptions$Builder.build(FirestoreOptions.java:213) ~[google-cloud-firestore-1.8.0.jar!/:1.8.0]
2019-07-22T10:24:38.586-07:00 [APP/PROC/WEB/0] [OUT] ... 65 common frames omitted
`

**Comment by meltsufin** [comment]
I believe this is caused by the fact that we haven't added support for Firestore in our `GcpCloudFoundryEnvironmentPostProcessor`.

**Comment by meltsufin** [comment]
@stevenweili I opened #1754 to fix this. Would you mind testing it?

**Comment by stevenweili** [comment]
that's super fast, not at all, I would love to give it a test.

**Comment by stevenweili** [comment]
it works! Mike! thanks~
