### ISSUE TITLE
Add original event details in CallbackListener (ListenableFutureCallback<String>).

### ISSUE THREAD

**Issue by sateekot** [spring-cloud/spring-cloud-gcp#2003]
If anyone wants to have fail back mechanism on failures to publish event to Pub/Sub, We should be able to access original message details along with the exception. As of now, we can access only exception details.
Ex:
com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=).
```19-10-31T21:32:00.400+0530 WARN Publishing to Demo topic failed.
com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=Demo).
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45) ~[gax-1.35.0.jar:1.35.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.35.0.jar:1.35.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.35.0.jar:1.35.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-1.35.0.jar:1.35.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.7.0.jar:?]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052) ~[guava-26.0-android.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[guava-26.0-android.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030) ~[guava-26.0-android.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871) ~[guava-26.0-android.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716) ~[guava-26.0-android.jar:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=Demo).
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.16.1.jar:1.16.1]
	... 23 more```

**Comment by meltsufin** [comment]
@sateekot Thanks for the report! Contributions are welcomed! 😉

**Comment by viniciusccarvalho** [comment]
If you look into the contract of `ListenableFuture`, there's two callbacks: `SuccessCallback<T>` and `FailureCallback`. 
If your Task completes successfully you receive the result, but in case of error the contract shows that you only receive the Exception.

If you want to keep track of what message originate that, you can do it on your code, after all you are the invoker of `publish(final String topic, PubsubMessage pubsubMessage) : ListenableFuture<T>`. 

And since you have control of what message you are sending you could do something like this : (this has been greatly simplified of course)
```java
String payload = "mymessage";
String topic = "projects/myproject/topics/spring-test"
ListenableFuture<String> result = template.publish(topic, payload);
result.addCallback(result1 -> {}, ex -> {
  // This closure you have access to the original message (be any object)
    System.out.println("Error sending " + payload);
});
``` 

It's really up to you with this info, you could store messages on a data structure and clear out the ones that have been sent, and take action on the ones that failed for instance.

**Comment by sateekot** [comment]
Thank You Vinicius. I have already started working on generic fix. I will raise pull request once I am done.

**Comment by meltsufin** [comment]
@artembilan What do you think of @viniciusccarvalho suggestion vs. supporting it directly in the callback. I think it can be a little more convenient to have the original message in the exception, but is that a good practice?

**Comment by artembilan** [comment]
Well, it's really unfortunate that Pub/Sub API doesn't correlate request with reply/exception in the `publish` logic, but at least we can do that in our `PubSubPublisherTemplate.publish()` logic.

The point is that with a `result.addCallback()` you don't have that flexibility to propagate a `Future` to upstream or even compose them.
So, what @viniciusccarvalho shows (welcome back, my friend, BTW! 😉) is a good workaround for target application, although it doesn't cover all the use-cases.

In the `public ListenableFuture<String> publish(final String topic, PubsubMessage pubsubMessage) {` method we could add a `pubsubMessage` into a `settableFuture.setException(throwable);` with the `MessageDeliveryException` wrapper.
This way we will have a request message context in case on error.

I also would present a request message in the case of `onSuccess()`, but that is going to break our API. And we can't have an overloaded methods with different return types...

We may consider that in the separate issue though...

**Comment by viniciusccarvalho** [comment]
Hey @artembilan Thank you my friend, it's good to be back :) I think your suggestion is what the PR #2020 was about 👍

**Comment by artembilan** [comment]
Yes, it looks like.
So, what is the question to me then, @meltsufin ? 😄 

Unfortunately I don't monitor the project closely any more, therefore may not see the whole picture. Sorry for inconvenience.
So, if you would like me to review the PR, you need to request that explicitly from the PR.

Thanks

**Comment by meltsufin** [comment]
You answered our question. Just wanted to hear your opinion on that approach in the PR. Sounds like you're onboard. It's nice to have @viniciusccarvalho back, contributing now from the other side. :smile:

**Comment by sateekot** [comment]
Thank you @meltsufin @artembilan @viniciusccarvalho for guiding me.

**Comment by meltsufin** [comment]
@sateekot Thanks for you contribution! Looking forward to more from you!
