### ISSUE TITLE
Error when shutting down spring-cloud-gcp-pubsub-binder-sample

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2032]
Ctrl-C on running binder sample server results in this error:

````
WARN 202983 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'inputBindingLifecycle'

org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'my-topic.my-group.errors' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:988) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]

````

And then, because shutdown failed, it takes the application a few minutes to time out and shutdown: 
```
2019-11-13 09:42:23.252  INFO 203501 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to shut down 1 bean with phase value 2147482647 within timeout of 30000: [inputBindingLifecycle]
```

The error handling logic itself seems to work fine.

**Comment by szisiu** [comment]
Hi, do you know when it will be solved?

**Comment by elefeint** [comment]
szisiu@, the issue has been fixed in `spring-cloud-stream`.

Out of curiosity, did you encounter this problem when trying our samples, or did you run into this problem elsewhere and found this GitHub issue through search?

**Comment by szisiu** [comment]
Hi @elefeint, I use spring-boot v. 2.2.1.RELEASE with `spring-cloud-gcp-pubsub-stream-binder:1.2.0.RELEASE` and `spring-cloud-stream:3.0.0.RELEASE` from spring cloud Hoxton.RELEASE.

My small pubsub consumer app looks like:

```java
@SpringBootApplication
public class ProcessorApp {
    public static void main(String[] args) throws IOException {
        SpringApplication.run(ProcessorApp.class, args);
        System.out.println("Hit 'Enter' to terminate");
        System.in.read();
    }
}

@EnableBinding(ChatConsumerBinding.class)
@Slf4j
@RequiredArgsConstructor
class ChatProcessor {
    @ServiceActivator(inputChannel = "chat.chat_group.errors")
    public void handleError(Message<?> message) {
        log.error(message.toString());
    }
    @StreamListener(ChatConsumerBinding.INPUT_CHANNEL)
    public void handle(Dto msg) {
        log.debug(msg.toString());
    }
}

interface ChatConsumerBinding {
    String INPUT_CHANNEL = "chat_input";

    @Input(ChatConsumerBinding.INPUT_CHANNEL)
    SubscribableChannel input();
}
```

application.properties:

```
spring.cloud.stream.bindings.chat_input.destination=chat
spring.cloud.stream.bindings.chat_input.group=chat_group
spring.cloud.stream.gcp.pubsub.bindings.chat_input.consumer.auto-create-resources=true
```

...and the error on CTRL-C or app termination (note the timeout, sending and receiving through pubsub works):

```
--2019-12-11 22:47:20.217 - INFO 4574 --- [           main] faultConfiguringBeanFactoryPostProcessor:213 : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
--2019-12-11 22:47:20.229 - INFO 4574 --- [           main] faultConfiguringBeanFactoryPostProcessor:300 : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
--2019-12-11 22:47:20.238 - INFO 4574 --- [           main] faultConfiguringBeanFactoryPostProcessor:460 : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
--2019-12-11 22:47:20.302 - INFO 4574 --- [           main] trationDelegate$BeanPostProcessorChecker:330 : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
--2019-12-11 22:47:20.305 - INFO 4574 --- [           main] trationDelegate$BeanPostProcessorChecker:330 : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
--2019-12-11 22:47:20.321 - INFO 4574 --- [           main] trationDelegate$BeanPostProcessorChecker:330 : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
--2019-12-11 22:47:21.123 - INFO 4574 --- [           main] o.s.s.c.ThreadPoolTaskScheduler         :171 : Initializing ExecutorService 'taskScheduler'
--2019-12-11 22:47:21.160 - INFO 4574 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry:256 : Looking up function 'null' with acceptedOutputTypes: []
--2019-12-11 22:47:21.555 - INFO 4574 --- [           main] o.s.s.c.ThreadPoolTaskScheduler         :171 : Initializing ExecutorService 'pubsubPublisherThreadPool'
--2019-12-11 22:47:21.560 - INFO 4574 --- [           main] o.s.s.c.ThreadPoolTaskScheduler         :171 : Initializing ExecutorService 'pubsubSubscriberThreadPool'
--2019-12-11 22:47:21.595 - INFO 4574 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor :171 : Initializing ExecutorService 'pubSubAcknowledgementExecutor'
--2019-12-11 22:47:22.104 - INFO 4574 --- [           main] o.s.c.s.m.DirectWithAttributesChannel   :64 : Channel 'application.chat_input' has 1 subscriber(s).
--2019-12-11 22:47:22.119 - INFO 4574 --- [           main] o.s.i.endpoint.EventDrivenConsumer      :107 : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
--2019-12-11 22:47:22.120 - INFO 4574 --- [           main] o.s.i.channel.PublishSubscribeChannel   :64 : Channel 'application.errorChannel' has 1 subscriber(s).
--2019-12-11 22:47:22.120 - INFO 4574 --- [           main] o.s.i.endpoint.EventDrivenConsumer      :159 : started bean '_org.springframework.integration.errorLogger'
--2019-12-11 22:47:22.121 - INFO 4574 --- [           main] o.s.i.endpoint.EventDrivenConsumer      :107 : Adding {service-activator:chatProcessor.handleError.serviceActivator} as a subscriber to the 'chat.chat_group.errors' channel
--2019-12-11 22:47:22.121 - INFO 4574 --- [           main] o.s.integration.channel.DirectChannel   :64 : Channel 'application.chat.chat_group.errors' has 1 subscriber(s).
--2019-12-11 22:47:22.122 - INFO 4574 --- [           main] o.s.i.endpoint.EventDrivenConsumer      :159 : started bean 'chatProcessor.handleError.serviceActivator'
--2019-12-11 22:47:24.438 - WARN 4574 --- [           main] o.s.c.g.s.b.p.PubSubMessageChannelBinder:745 : The provided errorChannel 'chat.chat_group.errors' is an instance of DirectChannel, so no more subscribers could be added and no error messages will be sent to global error channel. Resolution: Configure your own errorChannel as an instance of PublishSubscribeChannel
--2019-12-11 22:47:24.459 - INFO 4574 --- [           main] .s.c.g.p.i.i.PubSubInboundChannelAdapter:159 : started org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter@324e8baa
--Hit 'Enter' to terminate
--2019-12-11 22:47:55.448 - INFO 4574 --- [extShutdownHook] .s.c.g.p.i.i.PubSubInboundChannelAdapter:176 : stopped org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter@324e8baa
--2019-12-11 22:47:55.452 - WARN 4574 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor :264 : Failed to stop bean 'inputBindingLifecycle'
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'chat.chat_group.errors' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.removeBeanDefinition(DefaultListableBeanFactory.java:988)
	at org.springframework.context.support.GenericApplicationContext.removeBeanDefinition(GenericApplicationContext.java:328)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyBean(AbstractMessageChannelBinder.java:831)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.destroyErrorInfrastructure(AbstractMessageChannelBinder.java:818)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.access$300(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$2.afterUnbind(AbstractMessageChannelBinder.java:453)
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:168)
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:334)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.unbindInputs(AbstractBindableProxyFactory.java:156)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:66)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:68)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:85)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1021)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
-2019-12-11 22:48:25.458 - INFO 4574 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor :387 : Failed to shut down 1 bean with phase value 2147482647 within timeout of 30000: [inputBindingLifecycle]
--2019-12-11 22:48:25.460 - INFO 4574 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer      :107 : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
--2019-12-11 22:48:25.460 - INFO 4574 --- [extShutdownHook] o.s.i.channel.PublishSubscribeChannel   :64 : Channel 'application.errorChannel' has 0 subscriber(s).
--2019-12-11 22:48:25.461 - INFO 4574 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer      :193 : stopped bean '_org.springframework.integration.errorLogger'
--2019-12-11 22:48:25.461 - INFO 4574 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer      :107 : Removing {service-activator:chatProcessor.handleError.serviceActivator} as a subscriber to the 'chat.chat_group.errors' channel
--2019-12-11 22:48:25.462 - INFO 4574 --- [extShutdownHook] o.s.integration.channel.DirectChannel   :64 : Channel 'application.chat.chat_group.errors' has 0 subscriber(s).
--2019-12-11 22:48:25.462 - INFO 4574 --- [extShutdownHook] o.s.i.endpoint.EventDrivenConsumer      :193 : stopped bean 'chatProcessor.handleError.serviceActivator'
--2019-12-11 22:48:25.472 - INFO 4574 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor :208 : Shutting down ExecutorService 'pubSubAcknowledgementExecutor'
--2019-12-11 22:48:25.473 - INFO 4574 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler         :208 : Shutting down ExecutorService 'pubsubSubscriberThreadPool'
--2019-12-11 22:48:25.474 - INFO 4574 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler         :208 : Shutting down ExecutorService 'pubsubPublisherThreadPool'
--2019-12-11 22:48:25.479 - INFO 4574 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler         :208 : Shutting down ExecutorService 'taskScheduler'

```

**Comment by elefeint** [comment]
Please try `spring-cloud-stream:3.0.1.BUILD-SNAPSHOT`. The fix will be in the next service release.

**Comment by szisiu** [comment]
ok. will try.

**Comment by meltsufin** [comment]
Closing. Please reopen if you still see the issue with the new release.
