### ISSUE TITLE
PCF with spring cloud gcp (unable to bind vcap services)

### ISSUE THREAD

**Issue by deiveehan** [spring-cloud/spring-cloud-gcp#2297]
**Describe the bug**
I am using google storage service in Pivotal cloud, my application uses spring cloud gcp. 

My application works fine when I hardcode the gcp json in the application.yml, however when I use PCF, it is supposed to take the value that is defined in the PCF env. 

tried binding the vcap services to the application.yml as follows

gradle file:
id 'org.springframework.boot' version '2.2.6.RELEASE'

application.yml
storage:
credentials:
encoded-key: ${vcap.services.google-storage.credentials.[privateKeyData]}
project-id:

Also posted a similar issue in spring boot project as I was not sure if it is related to spring cloud gcp or spring boot. https://github.com/spring-projects/spring-boot/issues/20343

Error I get in the startup. 
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT ... 27 common frames omitted
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.storage.Storage]: Factory method 'storage' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 24
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT ... 52 common frames omitted
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT Caused by: java.lang.IllegalArgumentException: Illegal base64 character 24
2020-04-01T06:31:07.78-0400 [APP/PROC/WEB/0] OUT at java.util.Base64$Decoder.decode0(Base64.java:714) ~[na:1.8.0_232]

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by meltsufin** [comment]
First off, do you have the `spring-cloud-gcp-starter-cloudfoundry` in your application dependencies?
Second, you don't need to modify your `application.yml`. The starter will automatically populate the credentials for Storage.

The exception is saying that there is an illegal base64 character. So, I suspect that your `encoded-key` is not configured correctly in PCF.

I hope this gives you some leads.

**Comment by deiveehan** [comment]
I tried with Spring cloud dependency related jars in my build and that was not able to inject the vcap into my app configuration. 

After I added the spring-cloud-gcp-starter-cloudfoundry, the vcap configurations were able to inject into my application, it works fine now - thanks for your suggestion.

This can be closed.
