### ISSUE TITLE
Firestore - DocumentId autogeneration

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2428]
**Describe the bug**
If a `@DocumentId`field is null, the save operation fails with:
```
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.gcp.data.firestore.FirestoreTemplate.buildResourceName(FirestoreTemplate.java:405) ~[spring-cloud-gcp-data-firestore-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.cloud.gcp.data.firestore.FirestoreTemplate.createUpdateWrite(FirestoreTemplate.java:392) ~[spring-cloud-gcp-data-firestore-1.2.3.RELEASE.jar:1.2.3.RELEASE]
```

In regular Firestore API, document ID is automatically generated.

**Sample**
```
@Document
class Order {

  @DocumentId
  private String id;
 ...
}
```

```
@Repository
interface OrderRepository extends FirestoreReactiveRepository<Order> {}
```

```
Order order = new Order();
repository.save(order);
```

**Comment by Alos** [comment]
Same issue happens when calling `firestoreTemplate.save` directly
