### ISSUE TITLE
Application fails when Firebase-Admin is added as a dependency

### ISSUE THREAD

**Issue by pedroct92** [spring-cloud/spring-cloud-gcp#304]
I have been using the spring-cloud-gcp to process files on the datastorage and it seems to be working quite well on the 1.0.0-M version. However, I am trying to add firebase-admin to my project and the classes and services that uses the spring-cloud-gcp cannot be injected anymore.

```
 <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>5.7.0</version>
        </dependency>
```

The main part of the stack trace:

```
[INFO] GCLOUD: 2018-01-12 15:18:53.189 ERROR 35856 --- [           main] o.s.boot.SpringApplication               : Application startup failed
[INFO] GCLOUD: 
[INFO] GCLOUD: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'purchaseService': Unsatisfied dependency expressed through field 'gcsFileUtil'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gcsFileUtil': Unsatisfied dependency expressed through field 'gcsFile'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storage' defined in class path resource [org/springframework/cloud/gcp/storage/autoconfig/StorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.storage.Storage]: Factory method 'storage' threw exception; nested exception is java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]

```

Any ideas on this issue? I have checked firebase dependencies and seems that they are using a quite advanced version of the datastorage while the spring-cloud-gcp has a different version thus not adding the required version on my dependencies.

**Comment by meltsufin** [comment]
It looks like some dependency version mismatch on `google-api-client`. I would try forcing the version to `1.23.0` in your pom.
What do you mean by "they are using a quite advanced version of the datastorage"? Which version are they using?

**Comment by meltsufin** [comment]
@pedroct92 Closing the issue for now. If you're still having trouble, we'll re-open.
