### ISSUE TITLE
Problem with logging and old dependencies in M1

### ISSUE THREAD

**Issue by Mistic92** [spring-cloud/spring-cloud-gcp#352]
Hi. Since yesterday I have problem with stackdriver logging. 
I'm using google-cloud-java production 1.8.0 and beta 0.26.0 because of spring-cloud-gcp M1 limitations. 
When can we expect M2 release where are the newest dependencies? First release date was set to something like 28th december. Next was ~20th Jan and current is set to today 26th. 

When I try to log something it hangs and nothing more happens

```
2018-01-26 12:31:07.341[restartedMain] DEBUG o.s.c.e.PropertySourcesPropertyResolver:[getProperty:92] [ ]-        Could not find key 'spring.profiles.active' in any property source
2018-01-26 12:31:07.341[restartedMain] DEBUG o.s.c.e.PropertySourcesPropertyResolver:[getProperty:92] [ ]-        Could not find key 'spring.profiles.default' in any property source
2018-01-26 12:31:07.634[pool-2-thread-1] DEBUG i.n.c.DefaultChannelId:[debug:76] [ ]-        -Dio.netty.processId: 16056 (auto-detected)
2018-01-26 12:31:07.636[pool-2-thread-1] DEBUG i.n.u.NetUtil:[debug:76] [ ]-        -Djava.net.preferIPv4Stack: false
2018-01-26 12:31:07.636[pool-2-thread-1] DEBUG i.n.u.NetUtil:[debug:76] [ ]-        -Djava.net.preferIPv6Addresses: false
2018-01-26 12:31:07.737[pool-2-thread-1] DEBUG i.n.u.NetUtil:[debug:86] [ ]-        Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
2018-01-26 12:31:07.739[pool-2-thread-1] DEBUG i.n.u.NetUtil:[debug:81] [ ]-        Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
2018-01-26 12:31:07.851[pool-2-thread-1] DEBUG i.n.c.DefaultChannelId:[debug:76] [ ]-        -Dio.netty.machineId: c4:6e:1f:ff:fe:18:6d:29 (auto-detected)
2018-01-26 12:31:07.868[grpc-default-worker-ELG-2-2] DEBUG i.n.u.ResourceLeakDetectorFactory:[debug:76] [ ]-        Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@755c7993
2018-01-26 12:31:07.947[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2018-01-26 12:31:07.962[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2018-01-26 12:31:08.039[grpc-default-worker-ELG-2-2] DEBUG i.n.h.s.SslHandler:[debug:81] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
2018-01-26 12:31:08.046[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384}
2018-01-26 12:31:08.047[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:81] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND SETTINGS: ack=true
2018-01-26 12:31:08.050[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2018-01-26 12:31:08.060[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:81] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND SETTINGS: ack=true
2018-01-26 12:31:08.347[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND PRIORITY: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: logging.googleapis.com:443, :path: /google.logging.v2.LoggingServiceV2/WriteLogEntries, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.6.1, x-goog-api-client: gl-java/1.8.0_152 gccl/1.8.0 gapic/1.8.0 gax/1.9.0 grpc/1.6.1, grpc-accept-encoding: gzip, grpc-timeout: 49987978u, authorization: Bearer ya29.c.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2018-01-26 12:31:08.354[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND PRIORITY: streamId=3 padding=0 endStream=true length=213 bytes=00000000d00a2a70726f6a656374732f626c656e67652d3136333232312f6c6f67732f626c656e67652d6261636b656e6412250a06676c6f62616c121b0a0a70...
2018-01-26 12:31:09.217[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND PRIORITY: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Fri, 26 Jan 2018 11:31:09 GMT, alt-svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"] padding=0 endStream=false
2018-01-26 12:31:09.220[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND PRIORITY: streamId=3 padding=0 endStream=false length=5 bytes=0000000000
2018-01-26 12:31:09.224[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND PRIORITY: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, content-disposition: attachment] padding=0 endStream=true
2018-01-26 12:31:09.226[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND PING: ack=false length=8 bytes=0000000000000000
2018-01-26 12:31:09.226[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] OUTBOUND PING: ack=true length=8 bytes=0000000000000000
2018-01-26 12:31:14.920[threadDeathWatcher-1-1] DEBUG i.n.b.PoolThreadCache:[debug:81] [ ]-        Freed 1 thread-local buffer(s) from thread: threadDeathWatcher-1-1
2018-01-26 12:35:09.208[grpc-default-worker-ELG-2-2] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x6755d301, L:/192.168.0.108:41909 - R:logging.googleapis.com/172.217.20.202:443] INBOUND GO_AWAY: lastStreamId=3 errorCode=0 length=17 bytes=73657373696f6e5f74696d65645f6f7574
```

When I changed google-cloud-java to 1.15.0 and 0.33.0 logging started working but gax is crashing because spring-gcp have old deps

```
2018-01-26 12:44:00.997[restartedMain] DEBUG o.s.c.e.PropertySourcesPropertyResolver:[getProperty:92] [ ]-        Could not find key 'spring.profiles.active' in any property source
2018-01-26 12:44:00.997[restartedMain] DEBUG o.s.c.e.PropertySourcesPropertyResolver:[getProperty:92] [ ]-        Could not find key 'spring.profiles.default' in any property source
2018-01-26 12:44:01.410[grpc-default-executor-0] DEBUG i.n.c.DefaultChannelId:[debug:76] [ ]-        -Dio.netty.processId: 4068 (auto-detected)
2018-01-26 12:44:01.412[grpc-default-executor-0] DEBUG i.n.u.NetUtil:[debug:76] [ ]-        -Djava.net.preferIPv4Stack: false
2018-01-26 12:44:01.412[grpc-default-executor-0] DEBUG i.n.u.NetUtil:[debug:76] [ ]-        -Djava.net.preferIPv6Addresses: false
2018-01-26 12:44:01.517[grpc-default-executor-0] DEBUG i.n.u.NetUtil:[debug:86] [ ]-        Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
2018-01-26 12:44:01.518[grpc-default-executor-0] DEBUG i.n.u.NetUtil:[debug:81] [ ]-        Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
2018-01-26 12:44:01.629[grpc-default-executor-0] DEBUG i.n.c.DefaultChannelId:[debug:76] [ ]-        -Dio.netty.machineId: c4:6e:1f:ff:fe:18:6d:29 (auto-detected)
2018-01-26 12:44:01.647[grpc-default-worker-ELG-2-3] DEBUG i.n.u.ResourceLeakDetectorFactory:[debug:76] [ ]-        Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@5562bdbb
2018-01-26 12:44:01.681[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2018-01-26 12:44:01.706[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2018-01-26 12:44:01.754[grpc-default-worker-ELG-2-3] DEBUG i.n.h.s.SslHandler:[debug:81] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
2018-01-26 12:44:01.759[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384}
2018-01-26 12:44:01.760[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:81] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND SETTINGS: ack=true
2018-01-26 12:44:01.761[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2018-01-26 12:44:01.769[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:81] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND SETTINGS: ack=true
2018-01-26 12:44:02.112[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: logging.googleapis.com:443, :path: /google.logging.v2.LoggingServiceV2/WriteLogEntries, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty1.9.0, x-goog-api-client: gl-java/1.8.0_152 gccl/1.15.0 gapic/1.15.0 gax/1.16.0 grpc/1.9.0, grpc-accept-encoding: gzip, grpc-timeout: 49951091u, authorization: Bearer ya29.c.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, grpc-trace-bin: ] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2018-01-26 12:44:02.119[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=213 bytes=00000000d00a2a70726f6a656374732f626c656e67652d3136333232312f6c6f67732f626c656e67652d6261636b656e6412250a06676c6f62616c121b0a0a70...
2018-01-26 12:44:02.981[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Fri, 26 Jan 2018 11:44:03 GMT, alt-svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"] padding=0 endStream=false
2018-01-26 12:44:02.989[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=5 bytes=0000000000
2018-01-26 12:44:03.000[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, content-disposition: attachment] padding=0 endStream=true
2018-01-26 12:44:03.005[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] INBOUND PING: ack=false length=8 bytes=0000000000000000
2018-01-26 12:44:03.005[grpc-default-worker-ELG-2-3] DEBUG i.g.n.NettyClientHandler:[debug:86] [ ]-        [id: 0x44bddd55, L:/192.168.0.108:42331 - R:logging.googleapis.com/172.217.20.170:443] OUTBOUND PING: ack=true length=8 bytes=0000000000000000
2018-01-26 12:44:00.997[restartedMain] INFO  c.b.b.XXXXMainApp:[logStartupProfileInfo:593] [ ]-        No active profile set, falling back to default profiles: default
2018-01-26 12:44:03.017[restartedMain] DEBUG o.s.c.a.ClassPathBeanDefinitionScanner:[registerDefaultFilters:189] [ ]-        JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2018-01-26 12:44:03.017[restartedMain] DEBUG o.s.c.a.ClassPathBeanDefinitionScanner:[registerDefaultFilters:197] [ ]-        JSR-330 'javax.inject.Named' annotation found and supported for component scanning
2018-01-26 12:44:03.043[restartedMain] DEBUG o.s.b.f.s.DefaultListableBeanFactory:[getSingleton:221] [ ]-        Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
```
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/gax/grpc/ChannelProvider
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:697)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:640)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1188)
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:818)
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:804)
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:790)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.blenge.blenge.XXXXMainApp.main(XXXXMainApp.java:29)
Caused by: java.lang.ClassNotFoundException: com.google.api.gax.grpc.ChannelProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

**Comment by joaoandremartins** [comment]
@Mistic92 thanks for the nudge, we're working full steam to get M2 out the door as soon as possible!

If using snapshots is not an option for you, M2 shouldn't take too long to be released.

**Comment by Mistic92** [comment]
I wanted to use snapshots or anything else using jitpack but there is problem with paring pom. 

gradlew build --info

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.github.spring-cloud.spring-cloud-gcp:spring-integration-gcp:86ee89ea42.
  Required by:
      project :
> Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-pubsub:86ee89ea42.
  Required by:
      project :
   > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-pubsub:86ee89ea42.
      > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-pubsub/86ee89ea42/spring-cloud-gcp-pubsub-86ee89ea42.pom
         > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
            > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
               > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp/86ee89ea42/spring-cloud-gcp-86ee89ea42.pom
                  > Could not find org.springframework.cloud:spring-cloud-gcp-dependencies:86ee89ea42.
> Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starter-pubsub:86ee89ea42.
  Required by:
      project :
   > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starter-pubsub:86ee89ea42.
      > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-starter-pubsub/86ee89ea42/spring-cloud-gcp-starter-pubsub-86ee89ea42.pom
         > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starters:86ee89ea42.
            > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starters:86ee89ea42.
               > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-starters/86ee89ea42/spring-cloud-gcp-starters-86ee89ea42.pom
                  > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
                     > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
                        > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp/86ee89ea42/spring-cloud-gcp-86ee89ea42.pom
                           > Could not find org.springframework.cloud:spring-cloud-gcp-dependencies:86ee89ea42.
> Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starter-trace:86ee89ea42.
  Required by:
      project :
   > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starter-trace:86ee89ea42.
      > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-starter-trace/86ee89ea42/spring-cloud-gcp-starter-trace-86ee89ea42.pom
         > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starters:86ee89ea42.
            > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp-starters:86ee89ea42.
               > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-starters/86ee89ea42/spring-cloud-gcp-starters-86ee89ea42.pom
                  > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
                     > Could not resolve com.github.spring-cloud.spring-cloud-gcp:spring-cloud-gcp:86ee89ea42.
                        > Could not parse POM https://jitpack.io/com/github/spring-cloud/spring-cloud-gcp/spring-cloud-gcp/86ee89ea42/spring-cloud-gcp-86ee89ea42.pom
                           > Could not find org.springframework.cloud:spring-cloud-gcp-dependencies:86ee89ea42.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

```

**Comment by joaoandremartins** [comment]
Closing as M2 was just released.
Thanks for your patience!

**Comment by Mistic92** [comment]
Great job! :) But where is now spring-integration-gcp? It's used in samples, there is redirect at main README and it's used at https://spring.io/guides/gs/spring-cloud-gcp/

**Comment by joaoandremartins** [comment]
[We merged SI with the Storage and Pub/Sub modules](https://github.com/spring-cloud/spring-cloud-gcp/pull/360) and later [settled for the final package names](https://github.com/spring-cloud/spring-cloud-gcp/pull/387).

We'll need to update that getting started getting started guide.
