### ISSUE TITLE
PubSub integration crashing while reading headers

### ISSUE THREAD

**Issue by Mistic92** [spring-cloud/spring-cloud-gcp#434]
Hi. I just encountered problem with pubsub integration while it's reading headers of message.
I'm using 

```
    def springGcpVersion = "1.0.0.M2"
    compile("org.springframework.cloud:spring-cloud-gcp-pubsub:$springGcpVersion")
    compile("org.springframework.cloud:spring-cloud-gcp-starter-pubsub:$springGcpVersion")
    compile 'org.springframework.integration:spring-integration-core:5.0.1.RELEASE'
```

That's message payload from debug
```
GenericMessage [payload={"challengeId":"XXXXXXXX","RANDOM1":"RANOM","RANDOM2":"SOMETHING","trackingId":"5aXq7iERovyuW4wCdPzxDm","messageType":"SELF"}, headers={spanId=2d9ca7abceb4eda6, spanTraceId=5a8452550ce2c1d353acf05d17aa1147, nativeHeaders={spanTraceId=[5a8452550ce2c1d353acf05d17aa1147], spanId=[2d9ca7abceb4eda6], spanSampled=[0]}, messageSent=true, id=fe942721-1efb-b7ec-854b-cf340c22e5b2, spanSampled=0, gcp_pub_sub_acknowledgement=com.google.cloud.pubsub.v1.MessageDispatcher$3@7871f13d, contentType=text/plain;charset=UTF-8, timestamp=1518622869581}]
```
And that's error value and stacktrace from debug view

```
ex = {ClassCastException@11779} "java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map"
 detailMessage = "java.lang.String cannot be cast to java.util.Map"
 cause = {ClassCastException@11779} "java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map"
 stackTrace = {StackTraceElement[37]@11794} 
 suppressedExceptions = {Collections$UnmodifiableRandomAccessList@11387}  size = 0
```

```

 
org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98)
org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85)
org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69)
org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100)
org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:116)
org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:137)
org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:109)
org.springframework.integration.util.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1040)
org.springframework.integration.util.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:608)
org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:504)
org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:313)
org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:104)
org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:93)
org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:141)
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:438)
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:388)
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:197)
org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:81)
com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:405)
java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
java.util.concurrent.FutureTask.run(FutureTask.java)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by Mistic92** [comment]
When removed @Header(GcpHeaders.ACKNOWLEDGEMENT) AckReplyConsumer ackReplyConsumer from method parameter it's not crashing anymore so it's a temporary fix. 
Ofc with this need to use AUTO ack mode.

**Comment by artembilan** [comment]
@Mistic92 ,

Tell me, please, why stack trace is so abnormal?
Looks like not Java...
It's hard to read to determine the root of cause.

May we have a standard Java stack trace, please?

**Comment by Mistic92** [comment]
I had to copy it via Intellij debug view because at log there was only message without stacktrace. 
Ok I found normal stacktrace

```
org.springframework.messaging.MessageHandlingException: nested exception is java.lang.ClassCastException
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:107)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:93)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:141)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:438)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:388)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:197)
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:81)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: null
```

**Comment by artembilan** [comment]
May we see how does you message look before that exception?

Sounds strange for now though:
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map"
 detailMessage = "java.lang.String cannot be cast to java.util.Map
...
org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98)
```
is related to the code like:
```
private Map<String, List<String>> getNativeHeaders(Message<?> message) {
	return (Map<String, List<String>>) message.getHeaders().get(
				NativeMessageHeaderAccessor.NATIVE_HEADERS);
}
```
So, that gives us only one answer: your message has `nativeHeaders` header which is a `String` by type.

**Comment by Mistic92** [comment]
payload is the same what I send from another service(removed part of json). I'm not changing any headers.

```
GenericMessage [payload={"challengeId":"XXXXXXXX","RANDOM1":"RANOM","RANDOM2":"SOMETHING","trackingId":"5aXq7iERovyuW4wCdPzxDm","messageType":"SELF"}, headers={spanId=2d9ca7abceb4eda6, spanTraceId=5a8452550ce2c1d353acf05d17aa1147, nativeHeaders={spanTraceId=[5a8452550ce2c1d353acf05d17aa1147], spanId=[2d9ca7abceb4eda6], spanSampled=[0]}, messageSent=true, id=fe942721-1efb-b7ec-854b-cf340c22e5b2, spanSampled=0, gcp_pub_sub_acknowledgement=com.google.cloud.pubsub.v1.MessageDispatcher$3@7871f13d, contentType=text/plain;charset=UTF-8, timestamp=1518622869581}]
```

![pubsuberror](https://user-images.githubusercontent.com/2607098/36215832-7586f9b6-11ad-11e8-89e8-3e35bfe06302.png)

**Comment by artembilan** [comment]
Does it say anything to you?
```
nativeHeaders={spanTraceId=[5a8452550ce2c1d353acf05d17aa1147], spanId=[2d9ca7abceb4eda6], spanSampled=[0]}
```
So, this indeed is going to be a JSON on another side. 
Not sure how fix it from our side, but I can suggest you to `filter` (remove) such a header before sending over the network.

I think we may filter it as well, because it's not related to Pub/Sub at all. That's about STOMP protocol:
```
 * An extension of {@link MessageHeaderAccessor} that also stores and provides read/write
 * access to message headers from an external source -- e.g. a Spring {@link Message}
 * created to represent a STOMP message received from a STOMP client or message broker.
 * Native message headers are kept in a {@code Map<String, List<String>>} under the key
 * {@link #NATIVE_HEADERS}.
 *
 * <p>This class is not intended for direct use but is rather expected to be used
 * indirectly through protocol-specific sub-classes such as
 * {@link org.springframework.messaging.simp.stomp.StompHeaderAccessor StompHeaderAccessor}.
 * Such sub-classes may provide factory methods to translate message headers from
 * an external messaging source (e.g. STOMP) to Spring {@link Message} headers and
 * reversely to translate Spring {@link Message} headers to a message to send to an
 * external source.
 *
 * @author Rossen Stoyanchev
 * @since 4.0
 */
public class NativeMessageHeaderAccessor extends MessageHeaderAccessor {

	public static final String NATIVE_HEADERS = "nativeHeaders";
```

**Comment by Mistic92** [comment]
Hm, I don't know where it's coming from. For sending, I'm also using gcp integration.

**Comment by artembilan** [comment]
I think that is done in the `spring-cloud-sleuth`. See `MessagingTextMap`:
```
else {
	MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
	accessor.setHeader(NativeMessageHeaderAccessor.NATIVE_HEADERS, map);
	map.add(key, value);
}
```

So, we send it as a `Map`, but it is seriallized on the Pub/Sub side to JSON I guess and on the other side we don't deserialize it to `Map` back. Therefore such a `ClassCastException` issue.

/CC @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
If there's a bug in Sleuth can someone file an issue and show a sample how to replicate it please?

**Comment by artembilan** [comment]
No, I don't think that there is some bug, @marcingrzejszczak .

I just want to consult with you if it is OK to send tracing header over the network.
More over you might have met similar problem already. Therefore the question how to deal.

Only the way I see is like to filter all those headers who are not `String`.

Right now I see this code in the `PubSubMessageHandler`:
```
message.getHeaders().forEach(
				(key, value) -> headers.put(key, value.toString()));
```
This is exactly where we get that `Map` as a `String`. 
And even if we convert it into a string properly, there is no any hooks how to deserialize it to the `Map` back on the consumer side.

Well. Maybe as a solution to allow to transfer to the Pub/Sub only primitive types and `String` per se.
Since `Map` (or any collection) is not a primitive, we don't transfer it at all.

Thoughts ?

**Comment by marcingrzejszczak** [comment]
> I just want to consult with you if it is OK to send tracing header over the network.

That's absolutely what we need to be doing. We need the tracing headers so that the recipient knows that it should continue the trace

**Comment by joaoandremartins** [comment]
> Well. Maybe as a solution to allow to transfer to the Pub/Sub only primitive types and String per se.
Since Map (or any collection) is not a primitive, we don't transfer it at all.

As part of #161, I wanted to support sending objects as header values with Pub/Sub.
Haven't looked at what it takes to get there, or if it's possible, though.

**Comment by artembilan** [comment]
Good to know, @marcingrzejszczak !

Well, let's take a look to the message headers one more time!
```
headers={
    spanId=2d9ca7abceb4eda6, spanTraceId=5a8452550ce2c1d353acf05d17aa1147, 
    nativeHeaders={
                    spanTraceId=[5a8452550ce2c1d353acf05d17aa1147], 
                    spanId=[2d9ca7abceb4eda6], 
                    spanSampled=[0]}, 
    messageSent=true, 
    id=fe942721-1efb-b7ec-854b-cf340c22e5b2, 
    spanSampled=0,     
    gcp_pub_sub_acknowledgement=com.google.cloud.pubsub.v1.MessageDispatcher$3@7871f13d,     
    contentType=text/plain;charset=UTF-8, timestamp=1518622869581}]
```

So, looks like we are duplicating tracing headers in the top level and in the `nativeHeaders` as well.
I see like it is done with the mentioned above `MessagingTextMap`:
```
accessor.setHeader(key, value);
...
nativeAccessor.setNativeHeader(key, value);
```

Why do we do that? Why duplicate?
And I don't see that Sleuth is extracting these tracing headers from that `nativeHeaders` somehow...
Any explanations, @marcingrzejszczak , please ?

From here I think we are still good to filter this `Map nativeHeaders` before publishing to Pub/Sub.

**Comment by artembilan** [comment]
@joaoandremartins ,

that issue doesn't looks like related to the ``headers` concern because that one clearly describes the `payload` story. However the headers typing idea is good as well, but should be tackled in the separate issue. We may borrow the wisdom from Spring Kafka and its `DefaultKafkaHeaderMapper` where we use Jackson's `ObjectMapper` to serialize header value and store their original types in the separate `spring_json_header_types` header, which is used on the inbound side for the proper deserialization.

Right, that might be the way to go here as well.

Anyway we have several open questions:

1. As a workaround I suggest to [filter](https://docs.spring.io/spring-integration/docs/5.0.1.RELEASE/reference/html/messaging-transformation-chapter.html#header-filter) the `nativeHeaders` header before publishing to the Pub/Sub. That is what can be done without any modification to the Framework on the application level already right now. Just because we have all those tracing headers as flattened entries anyway.

2. Understand why SC-Sleuth uses  `nativeHeaders` and maybe fix the issue in the project to remove such an overhead.

3. Provide a quick fix to the `PubSubMessageHandler` do not send headers if they are not primitives and not strings.

Anything of these can be skipped. I don't insist. But the issue should provide some decision.

Thanks

**Comment by marcingrzejszczak** [comment]
> Why do we do that? Why duplicate?
> And I don't see that Sleuth is extracting these tracing headers from that nativeHeaders somehow...
> Any explanations, @marcingrzejszczak , please ?

Hmm I don't remember really. Maybe sth with websockets? @dsyer do you remember?

**Comment by Mistic92** [comment]
I need to check if it still happens on M3. Also I have a question. What should I see at console trace when I'm using pubsub and on both services I have trace dependency? Should I have one span from both services with subspans or separate? Currently, I have span only from service with api.

**Comment by joaoandremartins** [comment]
Not sure if I understood the question, but I think with the Spring Integration Pub/Sub channel adapters, you would only see a single span.

**Comment by artembilan** [comment]
@Mistic92 ,

The issue isn't closed, therefore there is no any fix or solution for you on the matter.

Not sure how your span relationship question is related to the issue.
Shouldn't better to ask it on Spring Cloud Sleuth project instead ?

**Comment by marcingrzejszczak** [comment]
Ping again to @dsyer about the native headers. I think you mentioned sth that the duplication is required for websockets but maybe in completely wrong

**Comment by dsyer** [comment]
Yes. Websockets. Whatever we do here has to assume that the native headers might be present probably.

**Comment by ChengyuanZhao** [comment]
It looks like this line (line 81) is related to the cause: https://github.com/spring-cloud/spring-cloud-gcp/blob/94bce62e3e635e143168dbba30c5ad3951327290/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/integration/inbound/PubSubInboundChannelAdapter.java

The payload is turned into a UTF 8 string it seems, so it makes sense that it can't be cast to a Map later on.

**Comment by joaoandremartins** [comment]
For RC1, is filtering out the `nativeHeaders` header altogether an acceptable stop-gap?

A reminder that Google Cloud Pub/Sub only supports headers in the `Map<String, String>` form.
We could think of serializing all outbound headers from `Object` to `String` using, e.g., Jackson JSON, and vice-versa for incoming ones.
But that would result in bigger message sizes and, therefore, additional charges for the users.
We could also make that flag-protected but, all in all, it's a feature that warrants some more thinking.

**Comment by mingzhao01** [comment]
@joaoandremartins  

Hello,

we are still seeing this issue after we upgraded the build to RC1. any idea?

thanks a lot

Ming

![screen shot 2018-07-03 at 11 12 13 am](https://user-images.githubusercontent.com/34241792/42228549-3f4e0192-7eb2-11e8-8139-82554619de5e.png)

**Comment by meltsufin** [comment]
@mingzhao01 What's the issue you're experiencing? I'm not sure how to interpret that code screenshot.

**Comment by Mistic92** [comment]
I found other error for RC1 maybe it's kind of related to this issue. 
I have mode set to MANUAL. I don't understand this line is set to byte[].class
https://github.com/spring-cloud/spring-cloud-gcp/blob/abcb52deaff7cc34fef06caa3027db1d8e76caf7/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/integration/inbound/PubSubInboundChannelAdapter.java#L54

```
2018-07-03 21:25:52.699[pool-15-thread-3] WARN  c.g.c.p.v.MessageDispatcher:[onFailure:153] [ ]-        MessageReceiver failed to processes ack ID: PTdFQV5AEkw2AkRJUytDCypYEU4EISE-MD5FU0RQBhYsXUZIUTcZCGhRDk9eIz81IChFFyMpAgJjXV8fYmhcXHUHUAsddyljIWMMRlAIRVl-d2s5MmlfWnAAVQ8RdHlkc2teFSnftZfnuY4iZh89WBJLLD5-, the message will be nacked.
org.springframework.cloud.gcp.pubsub.core.PubSubException: Sending Spring message failed.; nested exception is org.springframework.cloud.gcp.pubsub.support.converter.PubSubMessageConversionException: JSON deserialization of an object of type [B failed.; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `byte[]` out of START_OBJECT token
 at [Source: (byte[])"{"challengeId":"031c2986-7d6f-49b5-957d-95cc09246638","trackingId":"34185c20590c2ab96dbc3691269a57c6"}"; line: 1, column: 1]
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:88)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:403)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.cloud.gcp.pubsub.support.converter.PubSubMessageConversionException: JSON deserialization of an object of type [B failed.; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `byte[]` out of START_OBJECT token
 at [Source: (byte[])"{"challengeId":"031c2986-7d6f-49b5-957d-95cc09246638","trackingId":"34185c20590c2ab96dbc3691269a57c6"}"; line: 1, column: 1]
	at org.springframework.cloud.gcp.pubsub.support.converter.JacksonPubSubMessageConverter.fromPubSubMessage(JacksonPubSubMessageConverter.java:74)
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:80)
	... 8 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `byte[]` out of START_OBJECT token
 at [Source: (byte[])"{"challengeId":"031c2986-7d6f-49b5-957d-95cc09246638","trackingId":"34185c20590c2ab96dbc3691269a57c6"}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers.handleNonArray(PrimitiveArrayDeserializers.java:240)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$ByteDeser.deserialize(PrimitiveArrayDeserializers.java:498)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$ByteDeser.deserialize(PrimitiveArrayDeserializers.java:446)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1234)
	at org.springframework.cloud.gcp.pubsub.support.converter.JacksonPubSubMessageConverter.fromPubSubMessage(JacksonPubSubMessageConverter.java:70)
	... 9 common frames omitted
```

**Comment by meltsufin** [comment]
@Mistic92 It looks like your payload type is a JSON string. Since you didn't change the payload type to the desired class, the `JacksonPubSubMessageConverter` is trying to convert it to the default `byte[]` and fails.
Do you have a class to represent `challengeId` and `trackingId`? Or do you just want your Spring `Message<>` to contain the JSON as a String?

@artembilan I think we might want to stop automatically configuring the `JacksonPubSubMessageConverter`. It seems to be creating unexpected behavior for users. It might be better to leave it as a more explicit setting.

**Comment by Mistic92** [comment]
@meltsufin I have class for this but I'm using pubsub integration and expecting String which later I'm parsing with Jackson.
Ok I think I found how to setup type and it seems to work :) Thank you.
Is it missing in samples?

**Comment by meltsufin** [comment]
@Mistic92 The idea is that we can do the conversion from JSON to your custom payload type automatically in the adapter. So, you don't have to do it separately.
Indeed, since it's such a popular use case, we should have a sample for it.

**Comment by Mistic92** [comment]
Yes, this is cool idea and it should be in sample or just mentioned :) 
I don't know if this issue is fixed in RC1. I just get this error but message was send from M2 version

```
2018-07-03 22:33:13.375[pool-15-thread-3] WARN  c.g.c.p.v.MessageDispatcher:[onFailure:153] [ ]-        MessageReceiver failed to processes ack ID: PTdFQV5AEkw2AkRJUytDCypYEU4EISE-MD5FU0RQBhYsXUZIUTcZCGhRDk9eIz81IChFFyMpAgJjXV8fYmhcXHUHUAsddyljIWMMRlAIRVl-d2s5MmlfWnAAVQ8RdHlkc2teFSnftZfnuY4iZh89WBJLLD5-, the message will be nacked.
org.springframework.cloud.gcp.pubsub.core.PubSubException: Sending Spring message failed.; nested exception is org.springframework.messaging.MessageHandlingException: nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map, failedMessage=GenericMessage [payload=FinisherMessage(challengeId=031c2986-7d6f-49b5-957d-95cc09246638, trackingId=34185c20590c2ab96dbc3691269a57c6), headers={spanTraceId=5b3aab684aa80bdee670404a0fd24d5b, spanId=0e97644f56a49b63, gcp_pubsub_acknowledgement=com.google.cloud.pubsub.v1.MessageDispatcher$3@76a4c1e, nativeHeaders={spanTraceId=[5b3aab684aa80bdee670404a0fd24d5b], spanId=[0e97644f56a49b63], spanSampled=[0]}, messageSent=true, id=4e132ac8-c5d8-7c5e-4c17-40e450aab74c, spanSampled=0, timestamp=1530649993375}]
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:88)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:403)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.messaging.MessageHandlingException: nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:107)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:93)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:79)
	... 8 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98)
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85)
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:116)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:137)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:109)
	at org.springframework.integration.util.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1056)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:574)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:468)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:312)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:104)
	... 23 common frames omitted
```

**Comment by meltsufin** [comment]
@Mistic92 M2 is fairly old now and the Pub/Sub integration has evolved quiet a bit since then. Try M4 or RC1 please.
