### ISSUE TITLE
spring-cloud-gcp-storage  can not be used with FakeStorage or local emulator

### ISSUE THREAD

**Issue by Andy2003** [spring-cloud/spring-cloud-gcp#443]
If I use the spring-cloud-gcp-storage with

    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-nio</artifactId>
        <version>0.34.0-alpha</version>
    </dependency>

I will get the following error, b/c of missing implementation:

	Caused by: java.lang.UnsupportedOperationException: null
		at com.google.cloud.storage.contrib.nio.testing.FakeStorageRpc.create(FakeStorageRpc.java:98) ~[google-cloud-nio-0.34.0-alpha.jar:0.34.0-alpha]
		at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:111) ~[google-cloud-storage-1.15.0.jar:1.15.0]
		at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:108) ~[google-cloud-storage-1.15.0.jar:1.15.0]
		at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[gax-1.16.0.jar:1.16.0]
		at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[google-cloud-core-1.15.0.jar:1.15.0]
		at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[google-cloud-core-1.15.0.jar:1.15.0]
		at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:107) ~[google-cloud-storage-1.15.0.jar:1.15.0]
		... 107 common frames omitted

If I try to use it with a local running [emulator](https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/) configured by:

	@Bean
	public static Storage storage(GcpProjectIdProvider projectIdProvider) {
		return StorageOptions.newBuilder()
				.setCredentials(NoCredentials.getInstance())
				.setHeaderProvider(new UsageTrackingHeaderProvider(GcpStorageAutoConfiguration.class))
				.setProjectId(projectIdProvider.getProjectId())
				.setHost("http://localhost:8081")
				.build().getService();
	}

I will get the following error:

	Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
	Not Found

		at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065) ~[google-http-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[google-api-client-1.23.0.jar:1.23.0]
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:219) ~[google-cloud-storage-1.15.0.jar:1.15.0]
		... 113 common frames omitted

The running emulator will show the following:

    [datastore] Feb 19, 2018 12:10:52 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
    [datastore] INFO: Unknown request URI: /storage/v1/b?project=projectXYZ&projection=full

How to use this resource binder in local development setup without running against the real cloud?

**Comment by meltsufin** [comment]
Using the `google-cloud-nio`, are you overwriting the auto-configured `Storage` bean with something like:
```
  @Bean
  public Storage storage() {
    return LocalStorageHelper.getOptions().getService();
  }
```

**Comment by meltsufin** [comment]
As for using the "emulator",  you're referring to the Datastore emulator, not Storage emulator. AFAIK there is no Storage emulator in `gcloud`.

**Comment by Andy2003** [comment]
> Using the google-cloud-nio, are you overwriting the auto-configured Storage bean with something like:

yes exactly

> As for using the "emulator", you're referring to the Datastore emulator, not Storage emulator. AFAIK there is no Storage emulator in gcloud.

OK good to know that there is a difference

**Comment by meltsufin** [comment]
It looks like you're trying to create a bucket using `google-cloud-nio`.
I don't think it's necessary for the emulator. You can just create the blobs directly.
Can you share a bit more of how you're using Storage?

**Comment by Andy2003** [comment]
This is how I use it:

	@Autowired
	private ResourceLoader resourceLoader;

	@PostConstruct
	public void getResource() throws IOException {
		WritableResource wr = (WritableResource) resourceLoader.getResource("gs://test-bucket/foo.txt");
		try (OutputStream out = wr.getOutputStream()) {
			out.write("123".getBytes());
		}
	}

even if i don't use any bucket name like `resourceLoader.getResource("gs://foo.txt")` I get an exception:

	Caused by: java.lang.UnsupportedOperationException: Cannot get output stream for a storage bucket.
		at org.springframework.cloud.gcp.storage.GoogleStorageResourceBucket.getOutputStream(GoogleStorageResourceBucket.java:172)

**Comment by joaoandremartins** [comment]
That's because `gs://foo.txt` is the URI for a bucket, not a file. You must add the bucket to the URI.
I'm going to assume that using the Datastore emulator was an oversight, since it appears you want to test your storage code locally.

In that case, it seems like `FakeStorageRpc` could be the way to go. However, make sure you read the class's Javadoc:

```
 * <p>This class is <i>not</i> thread-safe. It's also (currently) limited in the following ways:
 * <ul>
 * <li>Supported
 *   <ul>
 *   <li>object create
 *   <li>object get
 *   <li>object delete
 *   <li>list the contents of a bucket
 *   <li>generations
 *   </ul>
 * <li>Unsupported
 *   <ul>
 *   <li>bucket create
 *   <li>bucket get
 *   <li>bucket delete
 *   <li>list all buckets
 *   <li>file attributes
 *   <li>patch
 *   <li>continueRewrite
 *   <li>createBatch
 *   <li>checksums, etags
 *   <li>IAM operations</li>
 *   </ul>
 * </ul>
```

It doesn't look like it supports creating buckets.

**Comment by Andy2003** [comment]
@joaoandremartins 

> That's because gs://foo.txt is the URI for a bucket,

I know. As you can see in my comment above I tried both: `gs://foo.txt`and `gs://test-bucket/foo.txt`

**Comment by meltsufin** [comment]
@Andy2003 Can you try against master? I think your issue is related to bucket auto-creation that we had in there before and removed with #433. Thanks!

**Comment by Andy2003** [comment]
#433 solved this issue
