### ISSUE TITLE
Make storage usable without bucket privileges

### ISSUE THREAD

**Issue by Andy2003** [spring-cloud/spring-cloud-gcp#444]
If i use  `spring-cloud-gcp-storage` my app will get the following error:

	com.google.cloud.storage.StorageException: foo@project-id.iam.gserviceaccount.com does not have storage.buckets.get access to bucket-name.
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:191)
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:315)
		at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:175)
		at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:172)
		at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
		at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
		at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
		at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:171)
		at org.springframework.cloud.gcp.storage.GoogleStorageResourceBucket.getGcsBucket(GoogleStorageResourceBucket.java:177)
		at org.springframework.cloud.gcp.storage.GoogleStorageResourceBucket.exists(GoogleStorageResourceBucket.java:79)
		at org.springframework.cloud.gcp.storage.GoogleStorageResourceObject.create(GoogleStorageResourceObject.java:168)
		at org.springframework.cloud.gcp.storage.GoogleStorageResourceObject.getOutputStream(GoogleStorageResourceObject.java:267)

This is because only the role `Storage Admin` will have the permission `storage.buckets.get`. To stay with the default roles an app needs the role `Storage Admin` to be able to use `spring-cloud-gcp-storage`. This is not desirable for security reasons, as the app could also create new buckets or delete existing ones.

There should be a mechanism to use this library also with roles like:

- Storage Object Admin (only needed for deletion / replacements)
- Storage Object Creator
- Storage Object Viewer

no need to touch any bucket

**Comment by meltsufin** [comment]
Have you tried setting `spring.cloud.gcp.credentials.scopes` to include the Admin role?
See [docs](https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.M2/reference/htmlsingle/#_scopes).

**Comment by joaoandremartins** [comment]
Not too sure if I understand this report, but it isn't true that only admins have access to `storage.buckets.get`, as evidenced by the [GCS documentation](https://cloud.google.com/storage/docs/json_api/v1/buckets/get).

`The caller must have READER permissions on the bucket.`

GCS applies ACLs on a per-bucket basis. If you want your service account to have access to a bucket, you should set the ACL for that bucket accordingly. I can't see any way around this, this is how the system is expected to behave.

Please let me know if I'm missing anything.

**Comment by Andy2003** [comment]
> Have you tried setting spring.cloud.gcp.credentials.scopes to include the Admin role

@meltsufin no I used default scope `https://www.googleapis.com/auth/devstorage.read_write`, I also see no way to include there admin roles

@joaoandremartins Why I need any permissions on the bucket? If the admin gives me the permissions to read / write / delete / list objects within a bucket that should be enough to use this library. 

This code snippet shows how to write to a bucket without having any bucket permission:

    BlobId blobId = BlobId.of("bucket-name", "file.txt");
    try (WriteChannel channel = storage.writer(BlobInfo.newBuilder(blobId).build())) {
        channel.write(ByteBuffer.wrap(StreamUtils.copyToByteArray(inputStream)));
    }

**Comment by joaoandremartins** [comment]
Thanks for the clarification @Andy2003.

After #433, we're not doing `bucket.get` anymore, so `Storage Admin` is no longer required.

I think you will still need `Storage Objects Admin` since, when the file resource is closed, the underlying storage client lib is trying to delete the object for some reason.

Let me know what you think.

**Comment by Andy2003** [comment]
@joaoandremartins `Storage Objects Admin`for deleting files, I will test the master with #433

**Comment by Andy2003** [comment]
#433 solved this issue
