### ISSUE TITLE
Annotating cloudSqlDataSourceProperties bean as primary causes NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by agzamovr** [spring-cloud/spring-cloud-gcp#482]
I have DataSourceProperties bean in configuration class which is annotated as primary. After adding Spring GCP to project i got following error:
```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' available: more than one 'primary' bean found among candidates: [dataSourceProperties, cloudSqlDataSourceProperties, spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determinePrimaryCandidate(DefaultListableBeanFactory.java:1384) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determineAutowireCandidate(DefaultListableBeanFactory.java:1344) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1113) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
```
I think, this is due to cloudSqlDataSourceProperties bean which is annotated as primary in GcpCloudSqlAutoConfiguration
https://github.com/spring-cloud/spring-cloud-gcp/blob/9b95d744775f85e8b33bad79a15d445dd50c09fe/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/sql/GcpCloudSqlAutoConfiguration.java#L167

**Comment by joaoandremartins** [comment]
Thanks for the report @agzamovr. Is your other data source supposed to help connecting to Cloud SQL?

Unfortunately, we require that `@Primary` annotation to be able to mutate `DataSourceProperties` created by spring-jdbc.

**Comment by artembilan** [comment]
Right, we do that by purpose in the Framework to meet Cloud SQL requirements.

What is your reason, @agzamovr , to have such a bean in your application?

Thanks

**Comment by agzamovr** [comment]
I need to connect to two datasources and one of them is primary. 
Actually i don't need whole GCP integration, just Google Pub/Sub service. But Spring GCP dependency pulls whole GCP integration components and thus CloudSQL start to interfere with my configuration. Is there a way to add only Google Pub/Sub integration to Gradle?

**Comment by joaoandremartins** [comment]
GCP Cloud SQL autoconfig is kicking in because you have `DataSource` and `EmbeddedDatabaseType` in your classpath (possibly from `spring-jdbc` for connecting to your other SQL instance).

If you add `spring.cloud.gcp.sql.enabled=false` to your `application.properties` file, the SQL autoconfig should stop giving you trouble. Let me know if that works.

**Comment by artembilan** [comment]
To be honest, that's not good from the target application design to try to reuse conventional configuration properties for different beans.  You should consider to introduce your own variant of the `DataSourceProperties` do not clash with the Spring Boot infrastructure.

**Comment by joaoandremartins** [comment]
@artembilan feel free to leave your ideas in #272.

If we want to reuse the `DataSource` autoconfiguration provided by `spring-jdbc` (including choosing between different connection pool options), I don't think we can create an alternative to `DataSourceProperties`...
Although we might be able to delete the previously existing `dataSourceProperties` bean from the context to ensure there's only one `DataSourceProperties` bean in the context? In that case, we wouldn't need the `@Primary` anymore, but it could cause problems when there is more than one `DataSource` (none that I can think of right now, though)...

**Comment by artembilan** [comment]
No, my point is that target application should not create its own `DataSourceProperties` bean.
Nothing more. It's really a problem from our perspective to have it as `@Primary` as well, but that's already different story... Yep! You have just mentioned it - #272 :smile:

**Comment by agzamovr** [comment]
@joaoandremartins it works, thank you very much.
@artembilan i have tried to removed DataSourceProperties to prevent clash with spring default datasource properties but cloud sql configuration still complained requiring database name until i turned it off completely as @joaoandremartins suggested.
