### ISSUE TITLE
NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing

### ISSUE THREAD

**Issue by agzamovr** [spring-cloud/spring-cloud-gcp#487]
Five minutes after application has launched i'm getting following errors every minute:
```
2018-03-26 14:42:11.265  INFO 11524 --- [           main] hello.PubSubApplication                  : Started PubSubApplication in 10.318 seconds (JVM running for 11.917)
2018-03-26 14:47:11.490  WARN 11524 --- [-worker-ELG-1-8] i.n.c.AbstractChannelHandlerContext      : Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@54c43cb4(success)

java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing(Lio/netty/channel/ChannelHandlerContext;ZLio/netty/buffer/ByteBuf;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;
	at io.grpc.netty.NettyClientHandler.sendPingFrame(NettyClientHandler.java:568) ~[grpc-netty-1.9.0.jar:1.9.0]
	at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:287) ~[grpc-netty-1.9.0.jar:1.9.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1041) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:295) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:186) [grpc-netty-1.9.0.jar:1.9.0]
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124) [grpc-netty-1.9.0.jar:1.9.0]
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32) [grpc-netty-1.9.0.jar:1.9.0]
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44) [grpc-netty-1.9.0.jar:1.9.0]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

**Comment by joaoandremartins** [comment]
@agzamovr you mind also sending your `pom.xml` file?
And what does your application do? What `spring-cloud-gcp` element is triggering this issue?

**Comment by agzamovr** [comment]
@joaoandremartins i'm running sample project from [this](https://github.com/spring-guides/gs-messaging-gcp-pubsub) repository for Google Pub/Sub service. Here is project dependencies:
```
dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.cloud:spring-cloud-gcp-starter-pubsub:1.0.0.M2")
    compile("org.springframework.integration:spring-integration-core")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}
```

**Comment by joaoandremartins** [comment]
@agzamovr I wasn't able to reproduce your issue.
I suspect there might be an old version of netty cached in your build system.
Try running `./gradlew clean run` and reopen this issue if you keep seeing the same error log.
