### ISSUE TITLE
Trace pubsub error - unknown enum value

### ISSUE THREAD

**Issue by Mistic92** [spring-cloud/spring-cloud-gcp#638]
Hi, I'm using Spring GCP trace M3 for few days and sometimes I'm getting this error when trying to send pubsub message. 

```
stacktrace=java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at com.google.devtools.cloudtrace.v1.TraceSpan$SpanKind.getNumber(TraceSpan.java:229)
	at com.google.devtools.cloudtrace.v1.TraceSpan$Builder.setKind(TraceSpan.java:1239)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.SpanTranslator.translate(SpanTranslator.java:74)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.SpanTranslator.translate(SpanTranslator.java:66)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.StackdriverTraceReporter.report(StackdriverTraceReporter.java:54)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.StackdriverTraceReporter.report(StackdriverTraceReporter.java:29)
	at org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration.lambda$adjustedReporter$0(TraceAutoConfiguration.java:87)
	at brave.internal.recorder.Recorder.finish(Recorder.java:112)
	at brave.RealSpan.finish(RealSpan.java:63)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:219)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.preSend(TracingChannelInterceptor.java:140)
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:589)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:435)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:150)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:142)
	at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:415)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:523)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:469)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:460)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy150.sendVisionMessage(Unknown Source)
at com.XXXX.XXXX.xxxx.service.impl.PubSubSenderServiceImpl.analyzeImageRequest(PubSubSenderServiceImpl.java:40)
```

**Comment by meltsufin** [comment]
Hi @Mistic92! The span kind is being detected as `UNRECOGNIZED`. I suspect it's because you're using Brave rather than Zipkin. @saturnism or @marcingrzejszczak might be able to help.

**Comment by Mistic92** [comment]
Hmm, that's interesting because I got this only few times. I need to "dig" more what is the cause :)

**Comment by meltsufin** [comment]
Do you see any traces show up at all? Maybe it only happens when there is an error.

**Comment by marcingrzejszczak** [comment]
> I suspect it's because you're using Brave rather than Zipkin

Hmmm, sth's wrong here. Brave is a tracer. Zipkin is a process that processes spans. You can't use one or the other. You can use both for example.

**Comment by meltsufin** [comment]
@marcingrzejszczak Sorry, that's due to my limited knowledge of the tracing libraries. Hence, reaching out to you and Ray for help. :smile:

**Comment by Mistic92** [comment]
I have created simple endpoint which is sending current date to pubsub topic. When I hit it few times error happens. 

```
java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at com.google.devtools.cloudtrace.v1.TraceSpan$SpanKind.getNumber(TraceSpan.java:229)
	at com.google.devtools.cloudtrace.v1.TraceSpan$Builder.setKind(TraceSpan.java:1239)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.SpanTranslator.translate(SpanTranslator.java:74)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.SpanTranslator.translate(SpanTranslator.java:66)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.StackdriverTraceReporter.report(StackdriverTraceReporter.java:54)
	at org.springframework.cloud.gcp.autoconfigure.trace.sleuth.StackdriverTraceReporter.report(StackdriverTraceReporter.java:29)
	at org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration.lambda$adjustedReporter$0(TraceAutoConfiguration.java:87)
	at brave.internal.recorder.Recorder.finish(Recorder.java:112)
	at brave.RealSpan.finish(RealSpan.java:63)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:219)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.preSend(TracingChannelInterceptor.java:140)
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:589)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:435)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:150)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:142)
	at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:415)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:523)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:469)
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:460)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy99.sendMessage(Unknown Source)
	at com.test.project.SenderServiceIImpl.pushMessage(SenderServiceIImpl.java:17)
	at com.test.project.auth.controller.PingPongController.helloWorld(PingPongController.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:76)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:716)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
```

And there is more! There we have SPAN_KIND_MAP with two values, CLIENT and SERVER
https://github.com/spring-cloud/spring-cloud-gcp/blob/3fdff1963d74c20f104a26175058d9d83bd4efb9/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/sleuth/SpanTranslator.java#L44

But there zipkinSpan.kind() returns "CONSUMER" which is not defined in map so we get undefined. 

https://github.com/spring-cloud/spring-cloud-gcp/blob/3fdff1963d74c20f104a26175058d9d83bd4efb9/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/sleuth/SpanTranslator.java#L73

**Comment by marcingrzejszczak** [comment]
The kind `CONSUMER` and `PRODUCER` come from messaging. It seems that @saturnism has forgotten to include those? ;)
