### ISSUE TITLE
Unable to Save or Retrieve ARRAY using java.util.List

### ISSUE THREAD

**Issue by markmiddletonjci** [spring-cloud/spring-cloud-gcp#663]
I am attempting to use an ARRAY of String column in Spanner.

Column              | Type                             | Nullable
language_code | ARRAY<STRING(10)>  | No

My model object has an attribute as:

@Column(name = "language_code")
private List<String> languages;

When I attempt to save or retrieve from Spanner I get the following exception:

org.springframework.cloud.gcp.data.spanner.core.mapping.SpannerDataException: The value in column with name language_code could not be converted to the corresponding property in the entity. The property's type is interface java.util.List.
	at org.springframework.cloud.gcp.data.spanner.core.convert.MappingSpannerReadConverter.lambda$read$0(MappingSpannerReadConverter.java:147)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:328)
	at org.springframework.cloud.gcp.data.spanner.core.convert.MappingSpannerReadConverter.read(MappingSpannerReadConverter.java:110)
	at org.springframework.cloud.gcp.data.spanner.core.convert.MappingSpannerConverter.mapToList(MappingSpannerConverter.java:91)
	at org.springframework.cloud.gcp.data.spanner.core.convert.MappingSpannerConverter.mapToList(MappingSpannerConverter.java:83)
	at org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.query(SpannerTemplate.java:123)
	at org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.query(SpannerTemplate.java:129)
	at org.springframework.cloud.gcp.data.spanner.repository.query.SpannerStatementQueryExecutor.executeQuery(SpannerStatementQueryExecutor.java:64)
	at org.springframework.cloud.gcp.data.spanner.repository.query.PartTreeSpannerQuery.execute(PartTreeSpannerQuery.java:60)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy102.findByBusinessUnitId(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
 
[https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-docs/src/main/asciidoc/spanner.adoc#lists]

**Comment by markmiddletonjci** [comment]
Sorry, I forgot to mention I am using:

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
            <version>1.0.0.M3</version>
</dependency>

**Comment by ChengyuanZhao** [comment]
@markmiddletonjci In M3 (but no longer required in coming versions) there is the`@ColumnInnerType` annotation for Lists. 

Would you mind giving this a try?
```
@column(name = "language_code")
@ColumnInnerType(innerType = String.class)
private List languages;
```

**Comment by markmiddletonjci** [comment]
Hello @ChengyuanZhao Thank you.  This has resolved my issue.
