### ISSUE TITLE
Startup Error from Spanner when only using Spring Cloud GCP CloudSQL MySQL

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#693]
Using Spring Cloud GCP 1.0.0.M3.

I _think_ this is been fixed in `master`: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/spanner/SpannerKeyRestSupportAutoConfiguration.java

Example: https://github.com/saturnism/spring-cloud-gcp-guestbook/tree/master/2-cloud-sql/guestbook-service

Configure `application-cloud.properties` with instance connection name.

Start: `./mvnw spring-boot:run -Dserver.port=8081 -Dspring.profiles.active=cloud`

Startup Error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'profileController' defined in URL [jar:file:
/home/devstar2401/.m2/repository/org/springframework/data/spring-data-rest-webmvc/3.0.7.RELEASE/spring-data-rest-webmvc-3.0.7.RELEASE.jar!/or
g/springframework/data/rest/webmvc/ProfileController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested excepti
on is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.data.rest.webmvc.c
onfig.RepositoryRestMvcConfiguration': Unsatisfied dependency expressed through field 'idConverters'; nested exception is org.springframework
.beans.factory.BeanCreationException: Error creating bean with name 'spannerKeyIdConverter' defined in class path resource [org/springframewo
rk/cloud/gcp/autoconfigure/spanner/SpannerKeyRestSupportAutoConfiguration.class]: Post-processing of merged bean definition failed; nested ex
ception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.gcp.autoconfigure.spanner.SpannerKeyIdConve
rter] from ClassLoader [java.net.URLClassLoader@e614d5b]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729) ~[spring-beans-5.0
.6.RELEASE.jar:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192) ~[spring-beans-5.0
.6.RELEASE.jar:5.0.6.RELEASE]
...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.data.rest.web
mvc.config.RepositoryRestMvcConfiguration': Unsatisfied dependency expressed through field 'idConverters'; nested exception is org.springfram
ework.beans.factory.BeanCreationException: Error creating bean with name 'spannerKeyIdConverter' defined in class path resource [org/springfr
amework/cloud/gcp/autoconfigure/spanner/SpannerKeyRestSupportAutoConfiguration.class]: Post-processing of merged bean definition failed; nest
ed exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.gcp.autoconfigure.spanner.SpannerKeyId
Converter] from ClassLoader [java.net.URLClassLoader@e614d5b]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotation
BeanPostProcessor.java:587) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91) ~[spring-beans-5.0.6.RELEASE.jar:
5.0.6.RELEASE]
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spannerKeyIdConverter' defined in class pa
th resource [org/springframework/cloud/gcp/autoconfigure/spanner/SpannerKeyRestSupportAutoConfiguration.class]: Post-processing of merged bea
n definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.gcp.autoconfi
gure.spanner.SpannerKeyIdConverter] from ClassLoader [java.net.URLClassLoader@e614d5b]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:
556) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:50
1) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
...
Caused by: java.lang.NoClassDefFoundError: Lorg/springframework/cloud/gcp/data/spanner/core/mapping/SpannerMappingContext;
        at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_171]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_171]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_171]
        at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:753) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE
]
        ... 66 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.gcp.data.spanner.core.mapping.SpannerMappingContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
        ... 70 common frames omitted

```

**Comment by saturnism** [comment]
All Spanner auto configuration should be conditional based on the `enabled` flag as well.

**Comment by saturnism** [comment]
We should avoid `@Autowire` as well. `SpannerMappingContext` should be passed in as a constructor whenever possible.

https://github.com/spring-cloud/spring-cloud-gcp/blob/b7e950404260a61b7fd09fd290f7211d2c344b7a/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/spanner/SpannerKeyIdConverter.java

**Comment by ChengyuanZhao** [comment]
Is this the same error as here ? https://github.com/spring-cloud/spring-cloud-gcp/issues/673

if so, it has been fixed since M3.
