### ISSUE TITLE
Guava Dependency Conflict

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#860]
Using with `Finchley.RELEASE` and `spring-cloud-starter-netflix-hystrix`

```
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at com.google.auth.oauth2.UserCredentials.<init>(UserCredentials.java:128) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.UserCredentials$Builder.build(UserCredentials.java:420) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.UserCredentials.fromJson(UserCredentials.java:161) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:171) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:166) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:112) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100) ~[google-auth-library-oauth2-http-0.9.1.jar:na]
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:59) ~[gax-1.28.0.jar:1.28.0]
	at org.springframework.cloud.gcp.core.DefaultCredentialsProvider.<init>(DefaultCredentialsProvider.java:110) ~[spring-cloud-gcp-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration.googleCredentials(GcpContextAutoConfiguration.java:54) ~[spring-cloud-gcp-autoconfigure-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration$$EnhancerBySpringCGLIB$$5ea3cfcb.CGLIB$googleCredentials$0(<generated>) ~[spring-cloud-gcp-autoconfigure-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration$$EnhancerBySpringCGLIB$$5ea3cfcb$$FastClassBySpringCGLIB$$1bb024ef.invoke(<generated>) ~[spring-cloud-gcp-autoconfigure-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration$$EnhancerBySpringCGLIB$$5ea3cfcb.googleCredentials(<generated>) ~[spring-cloud-gcp-autoconfigure-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 45 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_162]
	... 66 common frames omitted
```

Guava 15 is pulled in from the Hystrix starter:

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-netflix-hystrix:jar:2.0.0.RELEASE:compile
...
[INFO] |  +- com.netflix.hystrix:hystrix-javanica:jar:1.5.12:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.7:runtime
[INFO] |  |  +- org.ow2.asm:asm:jar:5.0.4:runtime
[INFO] |  |  +- org.aspectj:aspectjweaver:jar:1.8.13:compile
[INFO] |  |  \- com.google.guava:guava:jar:15.0:compile
```

/cc @spencergibb

**Comment by meltsufin** [comment]
@saturnism Is this still an issue? What can we do about it?

**Comment by spencergibb** [comment]
Does s-c-gcp manage guava? If it has a minimum dependency, it probably should.

**Comment by meltsufin** [comment]
We don't manage the version of Guava. Generally, we try to stay way the managing versions of deps we do not provide. We do however import `com.google.cloud:google-cloud-bom` in our BOM, and it also doesn't seem to manage the version of Guava.
/cc @garrettjonesgoogle

**Comment by garrettjonesgoogle** [comment]
@spencergibb Everything that uses Guava essentially has a minimum version of Guava that it needs, which is defined by the feature it uses that was most recently added to Guava. Thus, of course s-c-gcp has a minimum required version of Guava. 

But anyway, putting a version of Guava into a BOM doesn't help make sure that the user gets the highest minimum version among all of its dependencies; if there is another BOM that specifies a version of Guava, they could theoretically require a lower minimum version than google-cloud-bom, and if the user puts that other BOM first, Maven will pick it instead of the version that google-cloud-bom requires as its own minimum. Basically, Maven is of no help in a scenario when you want to pick the highest available version among a set of options.
