### ISSUE TITLE
Unable to get Cloud PubSub working with Kubernetes

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-gcp#868]
I'm trying to run a simple Spring Boot app that runs in Kubernetes. The app tries to setup a simple listener to a specific PubSub subscription like so:

```
//Setup Cloud Pubsub 
    @Bean
    public PubSubInboundChannelAdapter messageChannelAdapter(
                    @Qualifier("pubsubInputChannel") MessageChannel inputChannel,
                    PubSubTemplate pubSubTemplate) {
            PubSubInboundChannelAdapter adapter =
                            new PubSubInboundChannelAdapter(pubSubTemplate, "my-sub-test");
            adapter.setOutputChannel(inputChannel);
            return adapter;
    }
    
    @Bean
    public MessageChannel pubsubInputChannel() {
            return new DirectChannel();
    }
    
    @ServiceActivator(inputChannel = "pubsubInputChannel")
    public void messageReceiver(String payload) {
	logger.info("Message arrived! Payload: " + payload);
    }
```

The POM:

```
<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.6.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-pubsub</artifactId>
		</dependency>

		 <!-- Add Pub/Sub Starter -->
        <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
        </dependency>

        <!-- Add Spring Integration -->
        <dependency>
                <groupId>org.springframework.integration</groupId>
                <artifactId>spring-integration-core</artifactId>
        </dependency>
		

	</dependencies>

	<!-- Add Spring Cloud GCP Dependency BOM -->
  <dependencyManagement>
        <dependencies>
                <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-gcp-dependencies</artifactId>
                        <version>1.0.0.RC1</version>
                        <type>pom</type>
                        <scope>import</scope>
                </dependency>
        </dependencies>
  </dependencyManagement>
```

Also added:

```
<!-- Use Spring Milestone Repository -->
  <repositories>
        <repository>
                <id>spring-milestones</id>
                <name>Spring Milestones</name>
                <url>https://repo.spring.io/libs-milestone-local</url>
        </repository>
  </repositories>
```

The app loads fine locally and runs.

When running in K8 it complains about missing dependencies:

```
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative] at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:93) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:430) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97) ~[grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:242) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:558) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:551) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:489) [grpc-netty-shaded-1.13.1.jar!/:1.13.1] at 
```

The container is build with this Dokckerfile:
```
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

**Comment by artembilan** [comment]
According your stack trace it doesn't sound like Spring cloud GCP problem or even just Google Cloud Pub/Sub. 

Would be better if you report this issue against gRPC per se.

Thanks for understanding,

**Comment by artembilan** [comment]
Well, the `google-cloud-pubsub` is a transitive dependency via `spring-cloud-gcp-pubsub`: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-pubsub/pom.xml#L17

The `protobuf-java` is missed, indeed, but do we really need it? And still: how is it related to this project anyway?
Even if we can figure out what is the problem, we can't fix it here, from this project perspective: reading your stack trace, it sounds like there must be some SSL implementation which can't be loaded via `NativeLibraryLoader`. 

That's maximum what I can say from my Spring perspective...

**Comment by Alos** [comment]
If I don't add `protobuf-java` the app fails to compile with a:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultSubscriberFactory' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.gcp.pubsub.support.DefaultSubscriberFactory] from ClassLoader [sun.misc.Launcher$AppClassLoader@4aa298b7]
....
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.MessageOrBuilder
```

**Comment by artembilan** [comment]
Well, according `mvnw dependency:tree -pl :spring-cloud-gcp-starter-pubsub` command I have this tree:
```
[INFO] org.springframework.cloud:spring-cloud-gcp-starter-pubsub:jar:1.1.0.BUILD-SNAPSHOT
[INFO] +- org.springframework.cloud:spring-cloud-gcp-starter:jar:1.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-gcp-core:jar:1.1.0.BUILD-SNAPSHOT:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core:jar:1.35.0:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.9.9:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  |     \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |  +- com.google.api:api-common:jar:1.6.0:compile
[INFO] |  |  |  +- com.google.api:gax:jar:1.28.0:compile
[INFO] |  |  |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  |  |  \- com.google.auth:google-auth-library-oauth2-http:jar:0.9.1:compile
[INFO] |  |  |  |     \- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |  |  |        \- com.fasterxml.jackson.core:jackson-core:jar:2.9.6:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java-util:jar:3.5.1:compile
[INFO] |  |  |  |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.11.0:compile
[INFO] |  |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] |  |  \- org.springframework:spring-context:jar:5.0.7.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-aop:jar:5.0.7.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-beans:jar:5.0.7.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-expression:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-gcp-autoconfigure:jar:1.1.0.BUILD-SNAPSHOT:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.0.3.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter:jar:2.0.3.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot:jar:2.0.3.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-starter-logging:jar:2.0.3.RELEASE:compile
[INFO] |     |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |     |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |     |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.10.0:compile
[INFO] |     |  |  \- org.apache.logging.log4j:log4j-api:jar:2.10.0:compile
[INFO] |     |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |     +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |     \- org.yaml:snakeyaml:jar:1.19:runtime
[INFO] +- org.springframework.cloud:spring-cloud-gcp-pubsub:jar:1.1.0.BUILD-SNAPSHOT:compile
[INFO] |  \- com.google.cloud:google-cloud-pubsub:jar:1.35.0:compile
[INFO] |     +- com.google.cloud:google-cloud-core-grpc:jar:1.35.0:compile
[INFO] |     |  +- com.google.auth:google-auth-library-credentials:jar:0.9.1:compile
[INFO] |     |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
```

So, the `protobuf-java` dependency is there. Not sure how that happened for you that it is missed. Maybe Dokckerfile build issue...

**Comment by saturnism** [comment]
@Alos pinged me on chat. He's currently using Alpine-based image, which may not work well w/ gRPC. Advised using another base image and validate that works. If so, then can try `gcr.io/distroless/java`

**Comment by saturnism** [comment]
@Alos could i trouble you to confirm the fix, and closing the issue if Alpine was indeed the root cause?

**Comment by Alos** [comment]
Confirmed! 👍
