### ISSUE TITLE
Spanner cloud framework not allowing nested struct queries if not all columns are queried

### ISSUE THREAD

**Issue by nov1vinni** [spring-cloud/spring-cloud-gcp#894]
We are trying to leverage allowmissingcolumns=true on org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate.query(Class<T>, String, List<String>, Object[], SpannerQueryOptions)

Query used : select p.name as program_name, ARRAY(select as struct t.tier_id as tier_id, t.created_by as tier_created_by from tier t where t.PROGRAM_ID = p.PROGRAM_ID) as tiers from PROGRAM p

When it retireves parent entity there was no exception of a missing column but when it executed inner query to retrieve tiers in the below example we are seeing an exception 

```

org.springframework.cloud.gcp.data.spanner.core.mapping.SpannerDataException: Unable to read column from Spanner results: PROGRAM_ID
	at org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityReader.isMissingColumn(ConverterAwareMappingSpannerEntityReader.java:129)
	at org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityReader.shouldSkipProperty(ConverterAwareMappingSpannerEntityReader.java:120)
	at org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityReader.lambda$read$0(ConverterAwareMappingSpannerEntityReader.java:94)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:329)
	at org.springframework.cloud.gcp.data.spanner.core.convert.ConverterAwareMappingSpannerEntityReader.read(ConverterAwareMappingSpannerEntityReader.java:92)
	at org.springframework.cloud.gcp.data.spanner.core.convert.SpannerEntityReader.read(SpannerEntityReader.java:35)
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.convertOrRead(StructPropertyValueProvider.java:85)
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.lambda$convertOrReadIterable$0(StructPropertyValueProvider.java:101)
	at java.util.ArrayList.forEach(Unknown Source)
	at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
	at org.springframework.cloud.gcp.data.spanner.core.convert.StructPropertyValueProvider.convertOrReadIterable(StructPropertyValueProvider.java:101)

```

Please see the attached stackTrace where when its doing a fetch of inner query, entityReader is sending allowmissingcolumns as false. 

![stacktrace](https://user-images.githubusercontent.com/2513330/43230531-370bc52c-902e-11e8-9189-7f2e3136c0c4.jpg)

**Comment by ChengyuanZhao** [comment]
Thank you for reporting this ; will make fix shortly.

**Comment by nov1vinni** [comment]
Thanks chens. Do you know whats the estimated timeframe you would be able to release your fix as we need to change our queries accordingly.

**Comment by ChengyuanZhao** [comment]
This change will be available immediately once the PR is merged in the 1.1.0.BUILD-SNAPSHOT version and will also be included in the next milestone release.

**Comment by nov1vinni** [comment]
sure am subscribed to the updates on your commit. Will wait for hte merge.

**Comment by nov1vinni** [comment]
@ChengyuanZhao  i dont see 1.1.0.BUILD-SNAPSHOT @https://mvnrepository.com/artifact/com.google.cloud/google-cloud-spanner . Can you please check ?
